[tool.poetry]
name = "dotfiles"
version = "0.1.0"
description = ""
authors = ["Nils <nils@ungerichtet.de>"]

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^4.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
