#+title:     Yet another dotfiles repo
#+author:    Nils
#+email:     nils@ungerichtet.de
#+auto-tangle: f

* About this repo

This repo contains a poetry project with which my personal tools and settings can be deployed on a host machine.
The automation tool [[https://docs.ansible.com/ansible/latest/index.html][Ansible]] is used to install and configure all packages.

* Requirements

- Arch Linux or any derivate
- Python >= 3, installed using ~install.sh~ file

* Using

Read the complete chpater before using. The root of using this repo is the ~install.sh~ file.

#+begin_src sh
./install.sh work
#+end_src

The install script takes the argument ~work~ or ~home~, which provides the two environments I'm using.
There is a file inside the setup folder as named as the argument.
They contain ansible playbooks, that only import playbooks from the playbooks directory.
These ones contain the actual logic of installing and configuring all packages.

** Direnv

Both work and home use the direnv playbook to install [[https://direnv.net/][direnv]].

#+begin_quote
direnv is an extension for your shell. It augments existing shells with a new feature that can load and unload environment variables depending on the current directory.
#+end_quote

Create a file named ~.envrc~ with the following content.
This will activate thepython virtualenv when navigating to this dir on the terminal.

#+begin_src conf
use asdf-venv
layout poetry
#+end_src

** Custom configuration

Take a look at the file ~host_vars/localhost/vars.yml~.
This file contains descriptions on variables that are used during the installation process.
A user specific variable is named ~{{ local_... }}~.
You can set these variables inside the file ~host_vars/localhost/vault.yml~ to keep them out of git.

*** Ansible vault

You can use ~ansible-vault~ if you wish to encrypt these variables.
Ansible does need a password with which the file will be encrypted.
The `ANSIBLE_VAULT_PASSWORD_FILE` is a neat choice to lookup the password.
The file may contain the clear text password, which I don't recommend.
Instead provide a path to an executable file, that looks up the password.

**** Store the ansible password

~secret-tool~ can be used to store a password inside a local password storage like =gnome-keyring=.
Using ~playbooks/gnome_keyring.yml~ takes care of installing, if you wish to.

#+begin_src sh
secret-tool store --label "dotfiles vault" dotfiles vault
#+end_src

Enter the password, and your good to go.

**** Lookup the password

Create a ~mise.local.toml~ file with the following content.

#+begin_src shell
[env]
ANSIBLE_VAULT_PASSWORD_FILE = ".lookup_vault_pw"
#+end_src

The file must be executable in order to have ansible run it.
Using the command from storing the password, it must have the following content.

#+begin_example
#!/usr/bin/env sh
secret-tool lookup dotfiles vault
#+end_example

Ansible will lookup the password and you can use ~ansible-vault~ command to crud your custom settings.

#+begin_src sh
VAULT_CONF=host_vars/localhost/vault.yml
if [ ! -f "$VAULT_CONF" ]; then
    ansible-vault create $VAULT_CONF
fi
#+end_src
