#!/usr/bin/env bash
export SCRIPTPATH
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

# [ COLOR SCHEME ]
# Available themes:
#   - amber
#   - dracula
#   - gruvbox
#   - nord
#   - catppuccin
source "$SCRIPTPATH"/utils/colors.sh nord

# [ BASICS ]
# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Set the theme.ron config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# [ RUN STUFF ]
# picom
if [ -x "$(command -v picom)" ]; then
  picom --config "$HOME"/.config/picom/picom.conf &> /dev/null &
fi

# notifications
if [ -x "$(command -v dunst)" ]; then
  dunst -config "$HOME"/.config/leftwm/themes/current/conf/dunst.config &
fi

# [ WALLPAPER ]
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --restore
fi

# [ apps ]
nm-applet &
pamac-tray &
numlockx on &
/usr/lib/polkit-kde-authentication-agent-1 &
udiskie --tray &
"$SCRIPTPATH"/utils/polybar.sh

# [ ADJUST DISPLAY COLOR ]
systemctl --user start redshift-gtk.service
