#!/usr/bin/env bash
export SCRIPTPATH
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

# [ COLOR SCHEME ]
# Available themes:
#   - amber
#   - dracula
#   - gruvbox
#   - nord
#   - catppuccin
source "$SCRIPTPATH"/utils/colors.sh nord

# [ BASICS ]
# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Set the theme.ron config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# [ RUN STUFF ]
# picom
if [ -x "$(command -v picom)" ]; then
  picom --config "$HOME"/.config/picom/picom.conf &> /dev/null &
fi

# notifications
if [ -x "$(command -v dunst)" ]; then
  dunst -config "$HOME"/.config/leftwm/themes/current/conf/dunst.config &
fi

# [ WALLPAPER ]
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill --randomize $HOME/.local/share/wallpapers
fi

# [ apps ]
nm-applet &
pamac-tray &
numlockx on &
/usr/lib/polkit-kde-authentication-agent-1 &

# [ STATUSBAR ]
pkill polybar

index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &> /dev/null &
  let index=index+1
done

# [ ADJUST DISPLAY COLOR ]
systemctl --user start redshift-gtk.service
