# A minimal left prompt
format = """
[┌─ ](bold #88C0D0)$all $fill[─┐ ](#5E81AC)
[└─ ](bold #88C0D0)$character"""

# Inserts a blank line between shell prompts
add_newline = true

right_format = """$battery$time[─┘](#5E81AC)"""

[fill]
symbol = ''
style = '#5E81AC'

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[](#A3BE8C)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](red) "

[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
symbol = "󰏗 "

[battery]
full_symbol = "  "
charging_symbol = "󰂄 "
disabled = false
format = '[$symbol$percentage]($style) '

[[battery.display]]
threshold = 10
discharging_symbol = "  "
style = "bold fg:#f44336"

[[battery.display]]
threshold = 25
discharging_symbol = "  "
style = "bold fg:#ff9800"

[[battery.display]]
threshold = 50
discharging_symbol = "  "
style = "bold fg:#2196f3"

[[battery.display]]
threshold = 100
discharging_symbol = "  "
style = "bold fg:#4caf50"

[hostname]
ssh_only = true
format = '@[$hostname](bold fg:#81a1c1) '
disabled = false
ssh_symbol = " "

[time]
disabled = false
format = '[ $time ]($style) '
time_format = "%H:%M:%S"

[username]
style_user = 'fg:#88C0D0 bold'
style_root = 'fg:#d08770 bold'
format = '[$user]($style)'

## nerd font symbols
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
