# A minimal left prompt
format = """$username$hostname$directory$character"""

# move the rest of the prompt to the right
right_format = """$all"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
# ~/.config/starship.toml

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
disabled = false
format = '[$symbol$percentage]($style) '

[[battery.display]]
threshold = 10
style = "bold fg:#f44336"

[[battery.display]]
threshold = 25
style = "bold fg:#ff9800"

[[battery.display]]
threshold = 50
style = "bold fg:#2196f3"

[[battery.display]]
threshold = 100
style = "bold fg:#4caf50"

[time]
disabled = false
format = '[ $time ]($style) '
time_format = "%H:%M:%S"

