#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# https://wiki.archlinux.org/title/GNOME/Keyring#Launching_gnome-keyring-daemon_outside_desktop_environments_(KDE,_GNOME,_XFCE,_...)
dbus-update-activation-environment DISPLAY XAUTHORITY

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# keybindings daemon
# sxhkd -c ~/.config/leftwm/sxhkd/sxhkdrc &

# diversity of apps to start
nm-applet &
pamac-tray &
# xfce4-power-manager &
numlockx on &
blueberry-tray &
/usr/lib/polkit-kde-authentication-agent-1 &
# /usr/lib/xfce4/notifyd/xfce4-notifyd &
volumeicon &
# conky -c ~/.config/leftwm/system-overview &
#nitrogen --restore &
#firefox &
#dropbox &
#insync start &
#discord &

#boot picom
if [ -x "$(command -v picom)" ]; then
  picom --config $HOME/.config/picom/picom.conf &> /dev/null &
fi

# Set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --set-auto --random $HOME/.local/share/wallpapers
fi

# swap caps lock and escape
setxkbmap -option caps:swapescape

#mainbar
index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &> /dev/null &
  let index=index+1
done
