#+title: GNU Emacs Home of Captain-Proton
#+author: Captain-Proton
#+startup: showeverything
#+startup: indent

* Table of contents :toc:
- [[#startupinit-emacs][Startup/Init Emacs]]
- [[#custom-machine-settings][Custom machine settings]]
- [[#package-manager][Package Manager]]
- [[#general-keybindings][General Keybindings]]
- [[#fonts][Fonts]]
  - [[#setup-font-face][Setup Font Face]]
  - [[#load-font-face][Load font face]]
- [[#emacs][Emacs]]
- [[#all-the-icons][All-the-icons]]
- [[#editorconfig][EditorConfig]]
- [[#feed-reader][Feed Reader]]
  - [[#elfeed][Elfeed]]
  - [[#elfeed-org][Elfeed Org]]
  - [[#elfeed-goodies][Elfeed Goodies]]
- [[#evil-mode][Evil Mode]]
  - [[#evil-snipe][Evil Snipe]]
  - [[#nerd-commenter][Nerd Commenter]]
  - [[#multiple-cursors][Multiple cursors]]
- [[#yas-snippets][YAS Snippets]]
- [[#company][Company]]
- [[#dired][Dired]]
  - [[#dired-open][Dired Open]]
  - [[#preview][Preview]]
  - [[#dired-sidebar][Dired Sidebar]]
- [[#emacs-gui-tweaks][Emacs GUI Tweaks]]
  - [[#zoom-inout][Zoom In/Out]]
  - [[#yes-no-maybe][Yes no (maybe)]]
  - [[#disable-the-bars][Disable the bars]]
  - [[#highlight-thing][Highlight thing]]
  - [[#theme][Theme]]
  - [[#modeline][Modeline]]
  - [[#minions][Minions]]
  - [[#ligatures][Ligatures]]
  - [[#line-numbers][Line Numbers]]
  - [[#rainbows][Rainbows]]
  - [[#escape-the-mini-buffer][Escape the mini buffer]]
  - [[#focus-help-window][Focus help window]]
  - [[#no-tabs][No tabs]]
  - [[#indent-guides-and-whitespaces][Indent Guides and Whitespaces]]
  - [[#tab-line][Tab-line]]
  - [[#window-management][Window management]]
- [[#dashboard][Dashboard]]
- [[#diminish][Diminish]]
- [[#flycheck][Flycheck]]
- [[#projectile][Projectile]]
- [[#vertico][Vertico]]
- [[#orderless][Orderless]]
- [[#save-history][Save History]]
- [[#consult][Consult]]
- [[#marginalia][Marginalia]]
- [[#embark][Embark]]
- [[#git][Git]]
  - [[#transient][Transient]]
  - [[#magit][Magit]]
  - [[#timemachine][Timemachine]]
  - [[#diff-hl][Diff-hl]]
- [[#hcl--hashicorp-language][HCL / Hashicorp Language]]
- [[#visual-fill-column][Visual fill column]]
- [[#writeroom-mode][Writeroom mode]]
- [[#org-mode][Org Mode]]
  - [[#personal-knowledge-base-using-roam][Personal Knowledge Base using Roam]]
  - [[#table-of-contents][Table of contents]]
  - [[#babel][Babel]]
  - [[#bullets][Bullets]]
  - [[#headerlevel-size][Header/Level size]]
  - [[#kanban][Kanban]]
  - [[#presentations][Presentations]]
- [[#lsp][LSP]]
  - [[#lsp-mode][LSP-Mode]]
  - [[#lsp-ui][LSP-UI]]
  - [[#sideline-lsp][Sideline LSP]]
  - [[#ansible][Ansible]]
  - [[#python][Python]]
  - [[#terraform][Terraform]]
  - [[#rust][Rust]]
- [[#perspective-mode][Perspective Mode]]
- [[#perspectiveprojectile][Perspective/Projectile]]
- [[#shell][Shell]]
  - [[#eshell][Eshell]]
- [[#templates][Templates]]
- [[#tldr][Tldr]]
- [[#transparency][Transparency]]
- [[#treemacs][Treemacs]]
- [[#tree-sitter][Tree Sitter]]
  - [[#auto-tree-sitter][Auto tree sitter]]
  - [[#folding][Folding]]
- [[#sudo-edit][Sudo Edit]]
- [[#which-key][Which key]]
- [[#inheritenv][Inheritenv]]
- [[#direnv][Direnv]]

* Startup/Init Emacs

#+begin_src emacs-lisp
(setq make-backup-files nil  ;; do not create backup files at all
      delete-old-versions t  ;; delete backup files (filename~) automatically
      create-lockfiles nil   ;; no need for .# lock files
      vc-follow-symlinks t   ;; don't ask every time to follow sym links to vc repos
      )
#+end_src

Emacs will prompt for creating intermediate dirs if they do not exist.
You have to enter =RET= twice in order to create the directory.
This advice will automatically create these dirs without asking.

#+begin_src emacs-lisp
(defadvice find-file (before make-directory-maybe (filename &optional wildcards) activate)
  "Create parent directory if not exists while visiting file."
  (unless (file-exists-p filename)
    (let ((dir (file-name-directory filename)))
      (unless (file-exists-p dir)
        (make-directory dir t)))))
#+end_src

* Custom machine settings

All settings that are unique to the machine should be kept inside the
=user-emacs-dir/local.el= file.

#+begin_src emacs-lisp
(defvar local-settings-file (expand-file-name "local.el" proton/config-directory))
(when (file-exists-p local-settings-file)
  (load local-settings-file))
#+end_src

* Package Manager

I'm using [[https://github.com/progfolio/elpaca][Elpaca]] here.
This project offers some nice features like:

- asynchronous package installs
- cloning original package source code
- improved package management UI

The following block initializes the package manager

#+begin_src emacs-lisp
(defvar elpaca-installer-version 0.8)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                  ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                  ,@(when-let* ((depth (plist-get order :depth)))
                                                      (list (format "--depth=%d" depth) "--no-single-branch"))
                                                  ,(plist-get order :repo) ,repo))))
                  ((zerop (call-process "git" nil buffer t "checkout"
                                        (or (plist-get order :ref) "--"))))
                  (emacs (concat invocation-directory invocation-name))
                  ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                        "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                  ((require 'elpaca))
                  ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))
#+end_src

Packages installed via some commands are not loaded on subsequent Emacs sessions (after restarting).
To install AND load packages persistently (across Emacs restarts), I use the following elpaca macro after the installer.

#+begin_example

;; Install a package via the elpaca macro
;; See the "recipes" section of the manual for more details.

;; (elpaca example-package)
#+end_example

Add support for =use-package=.

#+begin_src emacs-lisp

;; Install use-package support
(elpaca elpaca-use-package
  ;;Enable Elpaca's use-package support
  (elpaca-use-package-mode)
  ;; Assume :ensure t unless otherwise specified.
  (setq use-package-always-ensure t))

;; Block until current queue processed.
(elpaca-wait)

#+end_src

* General Keybindings

[[https://github.com/noctuid/general.el][general.el]]

#+begin_src emacs-lisp

;;When installing a package which modifies a form used at the top-level
;;(e.g. a package which adds a use-package key word),
;;use `elpaca-wait' to block until that package has been installed/configured.
;;For example:

(use-package general
  :ensure t
  :demand t
  :config
  (general-evil-setup)
  ;; set 'SPC' as global leader key
  (general-create-definer proton/leader-keys
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix "SPC"
    :global-prefix "M-SPC") ;; access leader key in insert mode

  (defun proton/edit-config ()
    (interactive)
    (find-file (expand-file-name "config.org" proton/config-directory))
    )
  (defun show-message-log ()
    (interactive)
    (switch-to-buffer "*Messages*")
    )

  (proton/leader-keys
   "." '(find-file :wk "Find file")
   "f c" '(proton/edit-config :wk "Edit config.org")
   )

  (proton/leader-keys
   "b" '(:ignore t :wk "Buffer") ;; just a prefix, no real key binding
   "b b" '(switch-to-buffer :wk "Switch buffer")
   "b i" '(ibuffer :wk "IBuffer")
   "b k" '(kill-this-buffer :wk "Kill buffer")
   "b m" '(show-message-log :wk "*Messages*")
   "b n" '(next-buffer :wk "Next buffer")
   "b p" '(previous-buffer :wk "Previous buffer")
   "b r" '(revert-buffer :wk "Reload buffer")
   "b s" '(save-buffer :wk "Save buffer")
   )

  (proton/leader-keys
    "d" '(:ignore t :wk "Dired")
    "d d" '(dired :wk "Open dired")
    "d j" '(dired-jump :wk "Dired jump to current")
    "d p" '(peep-dired :wk "Peep-dired"))

  (proton/leader-keys
    "f" '(:ignore t :wk "Files/Fonts")
    )

  (proton/leader-keys
    "v" '(:ignore t :wk "Vanillamacs")
    "v r" '((lambda () (interactive)
            (load-file (expand-file-name "init.el" user-emacs-directory))
            (ignore (elpaca-process-queues)))
          :wk "Reload emacs config")
    "v R" '(restart-emacs :wk "Restart Emacs")
    "v q" '(kill-emacs :wk "Save and quit emacs"))

  (proton/leader-keys
   "h" '(:ignore t :wk "Help") ;; just a prefix, no real key binding
   "h f" '(describe-function :wk "Describe function")
   "h k" '(describe-key :wk "Describe key")
   "h K" '(describe-keymap :wk "Describe keymap")
   "h m" '(describe-mode :wk "Describe mode")
   "h p" '(elpaca-info :wk "Describe package")
   "h v" '(describe-variable :wk "Describe variable")
   )

  (proton/leader-keys
   "m" '(:ignore t :wk "Org")
   "m l" '(org-insert-link :wk "Insert link")
   )

  (proton/leader-keys
   "e" '(:ignore t :wk "Evaluate")
   "e b" '(eval-buffer :wk "Eval buffer")
   "e e" '(eval-expression :wk "Evaluate and elisp expression")
   "e r" '(eval-region :wk "Eval region")
   )

  (proton/leader-keys
   "o" '(:ignore t :wk "Open")
   "o d" '(dashboard-open :wk "Dashboard")
   "o e" '(eshell :wk "Open Eshell")
   )

  )
(elpaca-wait)
#+end_src

* Fonts

** Setup Font Face

#+begin_src emacs-lisp
(defvar proton/fixed-width-font "JetBrainsMono NF"
  "The font to use for monospaced (fixed width) text.")

(defvar proton/variable-width-font "Fira Sans"
  "The font to use for variable-pitch (document) text.")

(defun proton/load-default-fontaine-preset ()
  (interactive)
  (fontaine-set-preset 'regular))

(use-package fontaine
  :ensure t
  :after evil
  :general
  (proton/leader-keys
    "f d" '(proton/load-default-fontaine-preset :wk "Set default font preset")
    "f f" '(fontaine-set-preset :wk "Set font preset")
    )
  :config
  (setq fontaine-presets
        '((regular
           :default-height 110
           :line-spacing 0.16)
          (feedreader
           :default-family "JetBrainsMono Nerd Font"
           :default-height 140
           :default-weight regular
           :line-spacing 0.12)
          (presentation
           :default-height 180
           :line-spacing 0.16)
          (t
           :default-family "JetBrainsMono Nerd Font"
           :default-height 100
           :default-weight regular
           :fixed-pitch-family "JetBrainsMono Nerd Font"
           :variable-pitch-family "Fira Sans"
           :variable-pitch-height 120
           :variable-pitch-weight regular
           :line-spacing nil)))
    )

;; Makes commented text and keywords italics.
;; This is working in emacsclient but not emacs.
;; Your font must have an italic face available.
(set-face-attribute 'font-lock-comment-face nil
            :slant 'italic)
(set-face-attribute 'font-lock-keyword-face nil
            :slant 'italic)
(elpaca-wait)
#+end_src

** Load font face

Load last used font preset.
This should be done after a theme was loaded.
The theme may override the font setting.

#+begin_src emacs-lisp
(require 'fontaine)
(setq fontaine-latest-state-file (locate-user-emacs-file "fontaine-latest-state.eld"))

;; The other side of `fontaine-restore-latest-preset'.
(add-hook 'kill-emacs-hook #'fontaine-store-latest-preset)

;; Recover last preset or fall back to desired style from
;; `fontaine-presets'.
(with-eval-after-load 'doom-themes
  (fontaine-set-preset (or (fontaine-restore-latest-preset) 'regular))
  )
#+end_src
* Emacs

#+begin_src emacs-lisp
(use-package emacs
  :ensure nil
  :init
  ;; Add prompt indicator to `completing-read-multiple'.
  ;; We display [CRM<separator>], e.g., [CRM,] if the separator is a comma.
  (defun crm-indicator (args)
    (cons (format "[CRM%s] %s"
                  (replace-regexp-in-string
                   "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                   crm-separator)
                  (car args))
          (cdr args)))
  (advice-add #'completing-read-multiple :filter-args #'crm-indicator)

  ;; Do not allow the cursor in the minibuffer prompt
  (setq minibuffer-prompt-properties
        '(read-only t cursor-intangible t face minibuffer-prompt))
  (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)

  ;; Enable recursive minibuffers
  (setq enable-recursive-minibuffers t))
#+end_src

* All-the-icons

Icon set that can be used with dired and mode line.
Comes from [[https://github.com/domtronn/all-the-icons.el/tree/master][GitHub]].

#+begin_src emacs-lisp
(use-package all-the-icons
  :ensure t
  :if (display-graphic-p))

(use-package all-the-icons-dired
  :ensure t
  :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))
#+end_src

* EditorConfig

#+begin_quote
The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles.
#+end_quote

Taken from [[https://editorconfig.org/#overview][editorconfig.org]].
EditorConfig checks for a =.editorconfig= file inside the current directory of a file that is edited.
If none is found, it goes up the directory tree until a editorconfig with /root = true/ is found.
It then applies the style configured inside the editorconfig.
You can have multiple editorconfig files that are applied, as it stops only when the =root= advice is found.

#+begin_src emacs-lisp
(use-package editorconfig
  :ensure t
  :config
  (editorconfig-mode 1))
#+end_src

* Feed Reader

** Elfeed

#+begin_src emacs-lisp
(use-package elfeed
  :ensure t
  :after (general perspective)
  :bind
  (:map elfeed-show-mode-map
        ([remap elfeed-kill-buffer] . evil-delete-buffer))
  (:map elfeed-search-mode-map
        ([remap proton/persp-kill-current] . proton/quit-elfeed))
  :general
  (proton/leader-keys
    "o f" '(elfeed :wk "elfeed"))
  :config
  (setq elfeed-search-filter "@2-weeks-ago +unread")
  )

(with-eval-after-load 'elfeed
  (custom-set-faces
   '(elfeed-search-unread-title-face ((t :weight medium)))
   '(elfeed-search-title-face ((t :family "Vollkorn" :height 1.4)))
   )
  )

(defun proton/on-entering-elfeed()
  (fontaine-set-preset 'feedreader)
  (display-line-numbers-mode 0)
  )

(add-hook 'elfeed-search-mode-hook 'proton/on-entering-elfeed)

(defun proton/quit-elfeed()
  (interactive)
  (proton/load-default-fontaine-preset)
  (display-line-numbers-mode 1)
  (elfeed-search-quit-window)
  (persp-kill "elfeed")
  )

(general-advice-add 'elfeed
                    :before (lambda (&rest r) (persp-switch "elfeed")))
#+end_src


** Elfeed Org

#+begin_src emacs-lisp
(use-package elfeed-org
  :ensure t
  :after elfeed
  :init
  (elfeed-org)
  (setq rmh-elfeed-org-files (list "~/Org/elfeed.org")))
#+end_src

** Elfeed Goodies

#+begin_src emacs-lisp
(use-package elfeed-goodies
  :ensure t
  :after elfeed
  :config
  (elfeed-goodies/setup)
  (defun search-header/draw-wide (separator-left separator-right search-filter stats db-time)
    (let* ((update (format-time-string "%Y-%m-%d %H:%M:%S %z" db-time))
           (lhs (list
                 (powerline-raw (-pad-string-to "Date" (- 9 4)) 'powerline-active2 'l)
                 (funcall separator-left 'powerline-active2 'powerline-active1)
                 (powerline-raw (-pad-string-to "Feed" (- elfeed-goodies/feed-source-column-width 4)) 'powerline-active1 'l)
                 (funcall separator-left 'powerline-active1 'powerline-active2)
                 (powerline-raw (-pad-string-to "Tags" (- elfeed-goodies/tag-column-width 6)) 'powerline-active2 'l)
                 (funcall separator-left 'powerline-active2 'mode-line)
                 (powerline-raw "Subject" 'mode-line 'l)))
           (rhs (search-header/rhs separator-left separator-right search-filter stats update)))
      (concat (powerline-render lhs)
              (powerline-fill 'mode-line (powerline-width rhs))
              (powerline-render rhs))))
  (defun cp/elfeed-entry-line-draw (entry)
    "Print ENTRY to the buffer."
    (let* ((date (elfeed-search-format-date (elfeed-entry-date entry)))
           (title (or (elfeed-meta entry :title) (elfeed-entry-title entry) ""))
           (title-faces (elfeed-search--faces (elfeed-entry-tags entry)))
           (feed (elfeed-entry-feed entry))
           (feed-title
            (when feed
              (or (elfeed-meta feed :title) (elfeed-feed-title feed))))
           (tags (mapcar #'symbol-name (elfeed-entry-tags entry)))
           (tags-str (concat "[" (mapconcat 'identity tags ",") "]"))
           (title-width (- (window-width) elfeed-goodies/feed-source-column-width
                           elfeed-goodies/tag-column-width 4))
           (title-column (elfeed-format-column
                          title (elfeed-clamp
                                 elfeed-search-title-min-width
                                 title-width
                                 elfeed-search-title-max-width)
                          :left))
           (tag-column (elfeed-format-column
                        tags-str (elfeed-clamp (length tags-str)
                                               elfeed-goodies/tag-column-width
                                               elfeed-goodies/tag-column-width)
                        :left))
           (feed-column (elfeed-format-column
                         feed-title (elfeed-clamp elfeed-goodies/feed-source-column-width
                                                  elfeed-goodies/feed-source-column-width
                                                  elfeed-goodies/feed-source-column-width)
                         :left))
           )
      (if (>= (window-width) (* (frame-width) elfeed-goodies/wide-threshold))
          (progn
            ;; (insert (propertize entry-score 'face 'elfeed-search-feed-face) " ")
            (insert (propertize date 'face 'elfeed-search-date-face) " ")
            (insert (propertize feed-column 'face 'elfeed-search-feed-face) " ")
            (insert (propertize tag-column 'face 'elfeed-search-tag-face) " ")
            ;; (insert (propertize authors-column 'face 'elfeed-search-tag-face) " ")
            (insert (propertize title 'face title-faces 'kbd-help title))
            )
        (insert (propertize title 'face title-faces 'kbd-help title)))))
  (setq elfeed-search-print-entry-function 'cp/elfeed-entry-line-draw)
  )
#+end_src

* Evil Mode

[[https://github.com/emacs-evil/evil][Evil - extensible vi layer for emacs]]

#+begin_src emacs-lisp

;; Expands to: (elpaca evil (use-package evil :demand t))
;;(use-package evil :demand t)
(use-package evil
  :ensure t
  :init  ;; tweak evil before loading it
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)  ;; do not load default evil keybindings
  (setq evil-vsplit-window-right t)
  (setq evil-split-window-below t)
  (evil-mode)
  (add-hook 'with-editor-mode-hook 'evil-insert-state)
  :config
  (evil-set-undo-system 'undo-redo)
  (proton/leader-keys
    "b N" '(evil-buffer-new :wk "Open a new empty buffer")
    "b k" '(evil-delete-buffer :wk "Evil delete buffer")
   )
)

(use-package evil-collection
  :ensure t
  :after evil
  :config
  ;; Do not uncomment this unless you want to specify each and every mode
  ;; that evil-collection should works with.  The following line is here 
  ;; for documentation purposes in case you need it.  
  ;; (setq evil-collection-mode-list '(calendar dashboard dired ediff info magit ibuffer))
  (add-to-list 'evil-collection-mode-list '(help dashboard dired ibuffer)) ;; evilify help mode
  (evil-collection-init))

(use-package evil-tutor
  :ensure t
  :after evil
  )
#+end_src

#+begin_src emacs-lisp
;; Using RETURN to follow links in Org/Evil 
;; Unmap keys in 'evil-maps if not done, (setq org-return-follows-link t) will not work
(with-eval-after-load 'evil-maps
  (define-key evil-motion-state-map (kbd "SPC") nil)
  (define-key evil-motion-state-map (kbd "RET") nil)
  (define-key evil-motion-state-map (kbd "TAB") nil))
#+end_src

Remap =:q= to close only the current buffer.

#+begin_src emacs-lisp
(global-set-key [remap evil-quit] 'evil-delete-buffer)
#+end_src

** Evil Snipe

#+begin_src emacs-lisp
(use-package evil-snipe
  :ensure t
  :after evil
  :config
  (evil-snipe-mode +1))
#+end_src

** Nerd Commenter
A Nerd Commenter emulation, help you comment code efficiently.
For example, you can press “99,ci” to comment out 99 lines.

#+begin_src emacs-lisp
(use-package evil-nerd-commenter
  :ensure t
  :after evil
  :bind
  ("C-/" . evilnc-comment-operator)
  :config
  (evilnc-default-hotkeys))
#+end_src

** Multiple cursors

There are two projects (perhaps more) that implement multiple cursors for emacs.
The first one is [[https://github.com/magnars/multiple-cursors.el][multiple-cursors.el]] which is in use by the author.
This project should be used in a standard emacs environment.
In contrast to this project is [[https://github.com/gabesoft/evil-mc][evil-mc]].
It does not look to be heavily maintained, but as a evil user it is installed here.

#+begin_src emacs-lisp
(use-package evil-mc
  :ensure t
  :after (evil general)
  :init
  (global-evil-mc-mode  1)
  )
#+end_src

* YAS Snippets

In combination with lsp-mode, company requires yasnippet to be available.
Take a look at the [[https://github.com/emacs-lsp/lsp-mode/issues/2913][github issue]].

#+begin_src emacs-lisp
(use-package yasnippet
  :init
  (yas-global-mode 1)
  )
#+end_src

* Company

#+begin_quote
Company is a text completion framework for Emacs. The name stands for "complete anything". It uses pluggable back-ends and front-ends to retrieve and display completion candidates.
#+end_quote

Taken from [[https://company-mode.github.io/][company-mode]].

#+begin_src emacs-lisp
(use-package company
  :ensure (:tag "1.0.2")
  :diminish
  :custom
  (company-minimum-prefix-length 1)
  (company-idle-delay 0.1)
  (company-global-modes '(not eshell-mode shell-mode))
  ;; Search other buffers with the same modes for completion instead of
  ;; searching all other buffers.
  (company-dabbrev-other-buffers t)
  (company-dabbrev-code-other-buffers t)
  ;; M-<num> to select an option according to its number.
  (company-show-numbers t)
  :config
  (setq company-idle-delay 0.1
        company-minimum-prefix-length 1)
  ;; Use company with text and programming modes.
  :hook ((text-mode . company-mode)
         (prog-mode . company-mode))
  )

(use-package company-box
  :ensure t
  :after company
  :diminish
  :hook (company-mode . company-box-mode))
#+end_src

* Dired

Dired is the built-in file manager of emacs.

#+begin_src emacs-lisp
(use-package dired
  :ensure nil
  :config
  ;; do not flood emacs opening new buffers with navigation in dired
  (setq dired-kill-when-opening-new-dired-buffer t)
  )
#+end_src

** Dired Open

Open files from dired using using custom actions.

#+begin_src emacs-lisp
(use-package dired-open
  :ensure t
  :after dired
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("png" . "sxiv")
                                ("mkv" . "vlc")
                                ("mp4" . "vlc"))))
#+end_src

** Preview

Preview file contents in a small window when navigating the file tree using dired.

#+begin_src emacs-lisp
(use-package dired-preview
  :ensure t
  :config
  ;; Enable `dired-preview-mode' in a given Dired buffer or do it
  ;; globally:
  (dired-preview-global-mode 1)
  )
#+end_src

** Dired Sidebar

Sidebar showing a filetree.
[[https://github.com/jojojames/dired-sidebar][Dired Sidebar on Github]].
Integrates well within emacs as dired is the base package.
Additional integration with magit, projectile and evil is great.

#+begin_src emacs-lisp
(use-package vscode-icon
  :ensure t
  :commands (vscode-icon-for-file)
  )
#+end_src

#+begin_src emacs-lisp
(use-package dired-sidebar
  :ensure t
  :after dired
  :commands (dired-sidebar-toggle-sidebar)
  :init
  (add-hook 'dired-sidebar-mode-hook
            (lambda ()
              (display-line-numbers-mode 0)
              (unless (file-remote-p default-directory)
                (auto-revert-mode))
              ))
  (proton/leader-keys
    "d s" '(dired-sidebar-toggle-sidebar :wk "Dired sidebar"))
  :config
  (push 'toggle-window-split dired-sidebar-toggle-hidden-commands)
  (push 'rotate-windows dired-sidebar-toggle-hidden-commands)

  (setq dired-sidebar-subtree-line-prefix "  ")
  (setq dired-sidebar-theme 'vscode)
  (setq dired-sidebar-width 45)
  (setq dired-sidebar-use-term-integration t)
  (setq dired-sidebar-use-custom-font t)
  )
#+end_src


* Emacs GUI Tweaks

** Zoom In/Out

#+begin_src emacs-lisp
(setq text-scale-mode-step 1.05)
(defun proton/text-scale-reset ()
  (interactive)
  (text-scale-adjust 0))
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "C-=") 'proton/text-scale-reset)
#+end_src

** Yes no (maybe)

Always use =y= and =n= instead of =yes= and =no= when emacs asks questions.
This is only available in emacs >= 29.

#+begin_src emacs-lisp
(setq use-short-answers t)
#+end_src

** Disable the bars

#+begin_src emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
#+end_src

** Highlight thing

#+begin_src emacs-lisp
(defun proton/set-highlight-thing-colors ()
  (interactive)
  (set-face-background 'highlight-thing (doom-darken (doom-color 'highlight) 0.5))
  (set-face-foreground 'highlight-thing (doom-lighten (doom-color 'fg) 0.5)))

(use-package highlight-thing
  :ensure t
  :init
  (global-highlight-thing-mode)
  :hook (highlight-thing-mode . proton/set-highlight-thing-colors)
  :config
  (setq highlight-thing-what-thing 'sexp) ;; sexp = symbol expression (https://en.wikipedia.org/wiki/S-expression)
  )
#+end_src

** Theme

#+begin_src emacs-lisp
(add-to-list 'custom-theme-load-path (expand-file-name (concat user-emacs-directory "themes/")))
(use-package doom-themes
  :ensure t
  :init
  :config
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled, t by default
        doom-themes-enable-italic t) ; if nil, italics is universally disabled, t by default

  ;; This is the default theme
  (load-theme 'doom-nord t)

  ;; Add "padding" around tabs, the colour must be added to correct the colouring
  (set-face-attribute 'tab-line-tab-current nil :box '(:line-width 8 :color "#2E3440"))
  (set-face-attribute 'tab-line-tab-inactive nil :box '(:line-width 8 :color "#272C36"))
  (custom-set-faces `(fringe ((t (:background nil))))) ; make fringe match the bg
)
#+end_src

** Modeline

#+begin_src emacs-lisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :config
  (setq doom-modeline-height 24      ;; sets modeline height
        doom-modeline-bar-width 5    ;; sets right bar width
        doom-modeline-persp-name t   ;; adds perspective name to modeline
        doom-modeline-persp-icon t   ;; adds folder icon next to persp name
        doom-modeline-minor-modes t  ;; show minor modes
    )
  ) 
#+end_src

** Minions

#+begin_quote
This package implements a nested menu that gives access to all known
minor modes (i.e., those listed in `minor-mode-list').
#+end_quote

Taken from [[https://github.com/tarsius/minions][GitHub]].

#+begin_src emacs-lisp
(use-package minions
  :ensure t
  :config (minions-mode 1)
  )
#+end_src

** Ligatures

Be sure to install any nerd fonts that include them ([[https://www.nerdfonts.com][nerdfonts.com]]).
After using the =fonts.yml= playbook, there should be at least one available.
The default font face of this emacs configuration needs one.

[[https://github.com/mickeynp/ligature.el][ligature.el on github]]

#+begin_src emacs-lisp
(use-package ligature
  :ensure t
  :config
  ;; Enable all JetBrains Mono ligatures in programming modes
  (ligature-set-ligatures '(prog-mode org-mode text-mode)
                          '("--" "---" "==" "===" "!=" "!==" "=!="
                            "=:=" "=/=" "<=" ">=" "&&" "&&&" "&=" "++" "+++" "***" ";;" "!!"
                            "??" "???" "?:" "?." "?=" "<:" ":<" ":>" ">:" "<:<" "<>" "<<<" ">>>"
                            "<<" ">>" "||" "-|" "_|_" "|-" "||-" "|=" "||=" "##" "###" "####"
                            "#{" "#[" "]#" "#(" "#?" "#_" "#_(" "#:" "#!" "#=" "^=" "<$>" "<$"
                            "$>" "<+>" "<+" "+>" "<*>" "<*" "*>" "</" "</>" "/>" "<!--" "<#--"
                            "-->" "->" "->>" "<<-" "<-" "<=<" "=<<" "<<=" "<==" "<=>" "<==>"
                            "==>" "=>" "=>>" ">=>" ">>=" ">>-" ">-" "-<" "-<<" ">->" "<-<" "<-|"
                            "<=|" "|=>" "|->" "<->" "<~~" "<~" "<~>" "~~" "~~>" "~>" "~-" "-~"
                            "~@" "[||]" "|]" "[|" "|}" "{|" "[<" ">]" "|>" "<|" "||>" "<||"
                            "|||>" "<|||" "<|>" "..." ".." ".=" "..<" ".?" "::" ":::" ":=" "::="
                            ":?" ":?>" "//" "///" "/*" "*/" "/=" "//=" "/==" "@_" "__" "???"
                            "<:<" ";;;"))
  ;; Enables ligature checks globally in all buffers. You can also do it
  ;; per mode with `ligature-mode'.
  (global-ligature-mode t))
#+end_src


** Line Numbers

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)
(global-visual-line-mode t)

;; Disable line numbers for some modes
(dolist (mode '(term-mode-hook
                dashboard-mode-hook
                eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

** Rainbows

The delimiters add colors to paratheses.

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :ensure t
  :hook (prog-mode . rainbow-delimiters-mode)
  )
#+end_src

#+begin_src emacs-lisp
(use-package rainbow-mode
  :ensure t
  :diminish
  :hook
  ((org-mode prog-mode) . rainbow-mode))
#+end_src

** Escape the mini buffer

You have to type escape three time to quit the mini buffer.
Decrease the amount to one.
/Hint: Use ~C-g~ to quit./

#+begin_src emacs-lisp
(global-set-key [escape] 'keyboard-escape-quit)
#+end_src

** Focus help window

#+begin_src emacs-lisp
(setq help-window-select t)
#+end_src

** No tabs

Don't use tabs! Never! Really!

#+begin_src emacs-lisp
;; Set default indentation to use spaces instead of tabs
(setq-default indent-tabs-mode nil)
#+end_src

** Indent Guides and Whitespaces

#+begin_src emacs-lisp
(use-package indent-bars
  :ensure (:host github :repo "jdtsmith/indent-bars")
  :custom
  (indent-bars-treesit-support t)
  (indent-bars-no-descend-string nil)
  (indent-bars-treesit-ignore-blank-lines-types '("module"))
  (indent-bars-treesit-wrap '((python argument_list parameters ; for python, as an example
                                      list list_comprehension
                                      dictionary dictionary_comprehension
                                      parenthesized_expression subscript)))
  :hook ((prog-mode yaml-mode) . indent-bars-mode)
  :config
  (setq
    indent-bars-color '(highlight :face-bg t :blend 0.2)
    indent-bars-pattern "."
    indent-bars-width-frac 0.1
    indent-bars-pad-frac 0.1
    indent-bars-zigzag nil
    indent-bars-color-by-depth nil
    indent-bars-highlight-current-depth nil
    indent-bars-display-on-blank-lines nil)
  )
#+end_src

Show the whitespace characters tabs, spaces and trailing.
=face= is required to use them, see doc of =whitespace-style=.
The style is adjusted to match the used nord theme.

#+begin_src emacs-lisp
(use-package whitespace
  :ensure nil
  :init
  (global-whitespace-mode)
  :config
  ;; Don't enable whitespace for.
  (setq-default whitespace-global-modes
                '(not shell-mode
                      help-mode
                      text-mode
                      magit-mode
                      magit-diff-mode
                      ibuffer-mode
                      dired-mode
                      occur-mode))
  (setq
    whitespace-style '(face tabs tab-mark spaces space-mark trailing))
  (custom-set-faces
   '(whitespace-space ((t (:foreground "#4c566a" :background unspecified)))))
  )
#+end_src

** Tab-line

Not to mix up with =tab-bar=.
=tab-line= displays buffers specific for the current window!

#+begin_src emacs-lisp
(use-package tab-line
  :ensure nil
  :init
  (global-tab-line-mode t)
  :config
  (setq tab-line-new-button-show nil  ;; do not show add-new button
        tab-line-close-button-show nil  ;; do not show close button
        )
  ;; do not use :bind C-<next> ... they are bound in global.el
  (define-key (current-global-map) [remap scroll-right] 'previous-buffer)
  (define-key (current-global-map) [remap scroll-left] 'next-buffer)
  )
(require 'tab-line)

#+end_src

** Window management

#+begin_src emacs-lisp
(with-eval-after-load 'evil
  (proton/leader-keys
    "w" '(:ignore t :wk "Windows")
    "w c" '(evil-window-delete :wk "Close current window")
    "w |" '(evil-window-vsplit :wk "Split left/right (|)")
    "w -" '(evil-window-split :wk "Split top/bottom (-)")
    "w w" '(evil-window-next :wk "Next window")
    "w W" '(evil-window-prev :wk "Previous window")
    )
  )
#+end_src

Automatically resize windows when creating new ones or switching using =evil-window-*=.
Used to gain better resizing rather than just split windows in half.

#+begin_src emacs-lisp
(use-package golden-ratio
  :ensure t
  :init
  (golden-ratio-mode 1)
  )
#+end_src

* Dashboard

#+begin_src emacs-lisp
(use-package dashboard
  :ensure t
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner (format "%s/.icons/emacs.png" (getenv "HOME")))  ;; use custom image as banner
  (setq dashboard-center-content t) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (bookmarks . 3)
                          (projects . 5)
                          (registers . 3)))
  (setq dashboard-projects-backend 'projectile)
  :custom
  (dashboard-modify-heading-icons '((recents . "file-text")
                                    (bookmarks . "book")))
  :config
  (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
  (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
  (dashboard-setup-startup-hook)
  (display-line-numbers-mode 0)
  )
#+end_src

* Diminish

#+begin_quote
This package implements hiding or abbreviation of the mode line displays (lighters) of minor-modes.
#+end_quote

Taken from [[https://github.com/myrjola/diminish.el][GitHub]].

So if you add =:diminish= to a =use-package= declaration, the minor mode is not displayed on the mode line.

#+begin_src emacs-lisp
(use-package diminish
  :ensure t
  )
#+end_src

* Flycheck

#+begin_quote
Modern on-the-fly syntax checking extension for GNU Emacs.
#+end_quote

Taken from [[https://github.com/flycheck/flycheck][GitHub]].
Go to the [[https://www.flycheck.org/en/latest/languages.html][flycheck webpage]] to get info regarding support languages.

#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :defer t
  :diminish
  :config (global-flycheck-mode))
#+end_src

* Projectile

[[https://github.com/bbatsov/projectile][Projectile on GitHub]]

#+begin_quote
Projectile is a project interaction library for Emacs.
#+end_quote

#+begin_src emacs-lisp
(use-package projectile
  :ensure t
  :diminish
  :config
  (projectile-mode +1)
  (proton/leader-keys
    "p" '(:ignore t :wk "Project")
    "p d" '(projectile-discover-projects-in-search-path :wk "Discover projects")
    "p e" '(projectile-edit-dir-locals :wk "Edit project .dir-locals.el")
    "p i" '(projectile-invalidate-cache :wk "Invalidate project cache")
    "p p" '(projectile-switch-project :wk "Switch project")
    "p r" '(projectile-recentf :wk "Recent project files")
    "SPC" '(projectile-find-file :wk "Find file in project")
  )
)
#+end_src


* Vertico

[[https://github.com/minad/vertico][Vertico on github]]

#+begin_quote
Vertico provides a performant and minimalistic vertical completion UI based on the default completion system.
#+end_quote

#+begin_src emacs-lisp
(use-package vertico
  :ensure t
  :bind (:map minibuffer-local-map
              ("M-A" . marginalia-cycle))
  :diminish
  :bind (:map vertico-map
         ("C-j" . vertico-next)
         ("C-k" . vertico-previous)
         ("C-f" . vertico-exit)
         ("?" . minibuffer-completion-help)
         ("M-RET" . minibuffer-force-complete-and-exit)
         ("M-TAB" . minibuffer-complete)
         :map minibuffer-local-map
         ("C-h" . backward-kill-word))
  :custom
  (vertico-cycle t)
  :init
  (vertico-mode))
#+end_src

* Orderless

#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :init
  (setq completion-styles '(orderless basic)
        completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion)))))
#+end_src

* Save History

#+begin_src emacs-lisp
(use-package savehist
  :ensure nil  ;; built-in to emacs, no package manager required
  :init
  (savehist-mode))
#+end_src

* Consult

[[https://github.com/minad/consult][Consult on GitHub]]

#+begin_quote
Consult provides search and navigation commands based on the Emacs completion function completing-read.
#+end_quote

#+begin_src emacs-lisp
(use-package consult
  :ensure t
  :diminish
  :config
  (proton/leader-keys
    "<" '(consult-project-buffer :wk "Consult buffer")
    "RET" '(consult-bookmark :wk "Consult bookmark")
    "f r" '(consult-recent-file :wk "Consult recent file")
    "m h" '(consult-org-heading :wk "Consult org heading")
    "s" '(:ignore t :wk "Search")
    "s r" '(consult-ripgrep :wk "Consult rg")
    "s g" '(consult-grep :wk "Consult grep")
    "s G" '(consult-git-grep :wk "Consult git grep")
    "s f" '(consult-find :wk "Consult find")
    "s F" '(consult-fd :wk "Consult fd")
    "s b" '(consult-line :wk "Consult line")
    "S" '(:ignore t :wk "Additional Search")
    "S y" '(consult-yank-from-kill-ring :wk "Consult yank from kill ring")
    "i" '(consult-imenu :wk "Consult imenu"))
  )
#+end_src

* Marginalia

[[https://github.com/minad/marginalia][Marginalia on GitHub]]

#+begin_src emacs-lisp
(use-package marginalia
  :ensure t
  :after vertico
  :custom
  (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil))
  :init
  (marginalia-mode))
#+end_src

* Embark

 #+begin_src emacs-lisp
(use-package embark
  :after evil
  :ensure t

  :bind
  (("C-." . embark-act)         ;; pick some comfortable binding
   ("C-," . embark-dwim)        ;; good alternative: M-.
   ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'
  (:map vertico-map
        ("C-x e" . embark-export))

  :init

  ;; Optionally replace the key help with a completing-read interface
  (setq prefix-help-command #'embark-prefix-help-command)

  :config

  ;; Hide the mode line of the Embark live/completions buffers
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))

;; Consult users will also want the embark-consult package.
(use-package embark-consult
  :ensure t ; only need to install it, embark loads it after consult if found
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

* Git

** Transient

Provides keyboard-driven "menus" inside magit.
There is also a built-in transient package which has nothing in common with this one.

#+begin_src emacs-lisp
(use-package transient
  :ensure t
  )
#+end_src

** Magit

The git client for emacs.

#+begin_src emacs-lisp
(use-package magit
  :ensure t
  :after (transient)
  :init
  ;; Do not call on :config as this block
  ;; is executed after opening magit
  (proton/leader-keys
    "g" '(:ignore t :wk "Git")
    "g g" '(magit :wk "Open magit buffer")
  )
  :commands
  (magit-status magit-get-current-branch)
  :custom
  (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1)
  )
#+end_src

** Timemachine

git-timemachine is a program that allows you to move backwards and forwards through a file’s commits.  ‘SPC g t’ will open the time machine on a file if it is in a git repo.  Then, while in normal mode, you can use ‘CTRL-j’ and ‘CTRL-k’ to move backwards and forwards through the commits.

#+begin_src emacs-lisp
(use-package git-timemachine
  :ensure t
  :init
  (proton/leader-keys
    "g t" '(git-timemachine-toggle :wk "Toggle git timemachine")
  )
  :hook (evil-normalize-keymaps . git-timemachine-hook)
  :config
  (evil-define-key 'normal git-timemachine-mode-map (kbd "C-j") 'git-timemachine-show-previous-revision)
  (evil-define-key 'normal git-timemachine-mode-map (kbd "C-k") 'git-timemachine-show-next-revision)
)
#+end_src

** Diff-hl

Add margin to indicate version changes.

#+begin_src emacs-lisp
(use-package diff-hl
  :ensure t
  :init
  (add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
  (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)
  :config
  (global-diff-hl-mode)
  )
#+end_src

* HCL / Hashicorp Language

Used by different projects provided by hashicorp.
[[https://www.packer.io][Packer]] and [[*Terraform][Terraform]]/OpenTofu use the language.

#+begin_src emacs-lisp
(use-package hcl-mode
  :ensure t
  )
#+end_src

* Visual fill column

~visual-fill-column-mode~ is a small Emacs minor mode that mimics the effect of fill-column in visual-line-mode.
Instead of wrapping lines at the window edge, which is the standard behaviour of visual-line-mode, it wraps lines at fill-column.

#+begin_src emacs-lisp
(use-package visual-fill-column
  :ensure t
  )
#+end_src

* Writeroom mode

#+BEGIN_QUOTE
writeroom-mode is a minor mode for Emacs that implements a distraction-free writing mode similar to the famous Writeroom editor for OS X
#+END_QUOTE

#+begin_src emacs-lisp
(use-package writeroom-mode
  :ensure t
  :init
  (proton/leader-keys
    "z" '(:ignore t :wk "Zen")
    "z z" '(writeroom-mode :wk "Toggle zen")
    "z >" '(writeroom-increase-width :wk "Increase width")
    "z <" '(writeroom-decrease-width :wk "Decrease width")
    "z =" '(writeroom-adjust-width :wk "Adjust/Reset width")
    )
  )
#+end_src

* Org Mode

#+begin_src emacs-lisp
(setq org-return-follows-link t)
(setq org-hide-emphasis-markers t)

(use-package org
  :ensure nil
  :init
  (proton/leader-keys
    "m" '(:ignore t :wk "Org")
    "m e" '(org-edit-special :wk "Org edit special")
    "m t" '(org-todo :wk "Org todo")
    "m s" '(org-sort :wk "Org sort")
    )
  :config
  ;; This is considered highly unsafe!
  ;; But confirm again and again does lead to the same issue
  (setq org-confirm-babel-evaluate nil)
  (setq org-log-done 'time
        org-todo-keywords
        '((sequence
           "DOING(o)"           ; Things that are currently in work (work in progress)
           "TODO(t)"            ; Backlog items in kanban that should be executed
           "WAIT(w)"            ; A task that can not be set as DOING
           "|"                  ; Separate active and inactive items
           "DONE(d)"            ; Finished work ... yeah
           "CANCELLED(c@)"))    ; Cancelled things :(
        org-todo-repeat-to-state "TODO"
        org-ellipsis " ▾"
        org-hide-emphasis-markers t
        org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿"))
  )
#+end_src

If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!

#+begin_src emacs-lisp
(defvar proton/org-notes-dir (file-truename "~/Org/notes")
  "Directory containing all my org notes files")
(setq org-directory proton/org-notes-dir
      org-agenda-files (list proton/org-notes-dir))
#+end_src

Anything else at the moment can be set after org was loaded.

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (setq org-log-done 'time
    org-todo-keywords
    '((sequence
       "DOING(o)"           ; Things that are currently in work (work in progress)
       "TODO(t)"            ; Backlog items in kanban that should be executed
       "WAIT(w)"            ; A task that can not be set as DOING
       "|"                  ; Separate active and inactive items
       "DONE(d)"            ; Finished work ... yeah
       "CANCELLED(c@)"))    ; Cancelled things :(
    org-todo-repeat-to-state "TODO"
    org-ellipsis " ▾"
    org-hide-emphasis-markers t
    org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿"))
   (define-key org-src-mode-map (kbd "C-c C-c") 'org-edit-src-exit)
  )
#+end_src

** Personal Knowledge Base using Roam

Create the ~$HOME/Org/roam~ directory if it does not exists.
This directory will be used as ~org-roam-directory~.

#+begin_src emacs-lisp
(use-package org-roam
  :ensure t
  :after org
  :general
  (proton/leader-keys
    "m r" '(:ignore t :wk "Roam")
    "m r f" '(org-roam-node-find :wk "Find node")
    "m r i" '(org-roam-node-insert :wk "Insert node")
    )
  :config
  (setq proton/org-roam-home (format "%s/Org/roam" (getenv "HOME")))
  (when (not (file-directory-p proton/org-roam-home))
    (make-directory proton/org-roam-home 'parents))

  (setq org-roam-directory (file-truename proton/org-roam-home))
  (org-roam-db-autosync-mode)
  )

(defun proton/open-org-roam-perspective ()
    (interactive)
    (persp-switch "org-roam")
  )
(dolist (f '(org-roam-node-find org-roam-node-insert))
  (general-advice-add f :before #'proton/open-org-roam-perspective))
#+end_src

** Table of contents

Enable table of contents for org-mode and markdown-mode.

#+begin_src emacs-lisp
(use-package toc-org
  :ensure t
  :commands toc-org-enable
  :init
  (add-hook 'org-mode-hook 'toc-org-enable)
  ;; enable in markdown, too
  (add-hook 'markdown-mode-hook 'toc-org-mode)
  )
#+end_src

** Babel

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)
     (shell . t)
     (makefile . t)
     (plantuml . t)
     (js . t)
     (sql . t)
     (sqlite . t)
     ;; Add more languages as needed
     )))

  (setq org-src-fontify-natively t) ; Enable syntax highlighting in source blocks
#+end_src

** Bullets

By default emacs displays asterisks in org-mode for headers.
These can be adjusted by using =org-bullets=.
In addition the =org-indent-mode= is activated to automatically indent the content under a heading.

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
(use-package org-bullets
  :ensure t
  )
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

** Header/Level size

#+begin_src emacs-lisp
(require 'org-faces)

;; Make sure certain org faces use the fixed-pitch face when variable-pitch-mode is on
(set-face-attribute 'org-block nil
            :foreground 'unspecified
            :font proton/fixed-width-font
            :height 1.0
            :weight 'light)
#+end_src

#+begin_src emacs-lisp
(defun proton/org-colors-nord ()
  "Enable Nord colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#81a1c1" bold)
         (org-level-2 1.6 "#b48ead" bold)
         (org-level-3 1.5 "#a3be8c" semi-bold)
         (org-level-4 1.4 "#ebcb8b" normal)
         (org-level-5 1.3 "#bf616a" light)
         (org-level-6 1.2 "#88c0d0" light)
         (org-level-7 1.1 "#81a1c1" light)
         (org-level-8 1.0 "#b48ead" light)))
    (let ((face-name (car face))
          (height (nth 1 face))
          (foreground (nth 2 face))
          (weight (nth 3 face)))

      (set-face-attribute (car face) nil
                          :family proton/variable-width-font
                          :height height
                          :foreground foreground
                          :weight weight)
    )
  )
  (set-face-attribute 'org-table nil
                      :family proton/fixed-width-font
                      :weight 'normal
                      :height 1.0
                      :foreground "#88c0d0")
  )
(with-eval-after-load 'org
  (add-hook 'org-mode-hook 'proton/org-colors-nord))
#+end_src

#+begin_src emacs-lisp
(setq org-src-preserve-indentation t)
#+end_src

** Kanban

=org-kanban= ([[https://github.com/gizmomogwai/org-kanban][github]]) allows the creation of kanban boards in org documents.
Headers are used as card descriptions.
Create a new board for example using =M-x org-kanban/initialize-at-end=.

#+begin_src emacs-lisp
(use-package org-kanban
  :ensure t
  )
#+end_src

** Presentations

Use minimal style presentations using ~org-present~.

#+begin_src emacs-lisp
(use-package org-present
  :ensure t
  )
#+end_src


Define functions that should be executed entering and leaving
org-present.

#+begin_src emacs-lisp
(defun proton/org-present-prepare-slide (buffer-name heading)
  ;; Show only top-level headlines
  (org-overview)

  ;; Unfold the current entry
  (org-show-entry)

  ;; Show only direct subheadings of the slide but don't expand them
  (org-show-children))

(defun proton/org-present-start ()
  ;; Use visual-line-mode here to cause lines to be wrapped within the
  ;; centered document, otherwise you will have to horizontally scroll to see
  ;; them all!
  (setq visual-fill-column-width 110
        visual-fill-column-center-text t)

  ;; Center the presentation and wrap lines
  (visual-fill-column-mode 1)
  (visual-line-mode 1)
  (display-line-numbers-mode 0)
  (highlight-thing-mode 0)

  ;; Tweak font sizes
  (fontaine-set-preset 'presentation)

  ;; Set a blank header line string to create blank space at the top
  (setq header-line-format " ")

  ;; Display inline images automatically
  (org-display-inline-images)

  ;; Start in normal mode so slides can be cycled immediatly
  (evil-force-normal-state)
  )

(defun proton/org-present-end ()
  ;; Reset visual fill column values to default
  (setq visual-fill-column-width nil
        visual-fill-column-center-text nil)

  ;; Stop centering the document
  (visual-fill-column-mode 0)
  (visual-line-mode 0)
  (display-line-numbers-mode 1)
  (highlight-thing-mode 1)

  ;; Reset font customizations, default was nil
  (fontaine-set-preset 'regular)

  ;; Clear the header line string so that it isn't displayed
  (setq header-line-format nil)

  ;; Unfold everything to show the complete content
  (org-fold-show-all)

  ;; Stop displaying inline images
  (org-remove-inline-images)
  )
#+end_src

Register hooks with org-present.

#+begin_src emacs-lisp
(add-hook 'org-present-mode-hook 'proton/org-present-start)
(add-hook 'org-present-mode-quit-hook 'proton/org-present-end)
(add-hook 'org-present-after-navigate-functions 'proton/org-present-prepare-slide)
#+end_src

* LSP

** LSP-Mode

#+begin_quote
The Language Server protocol is used between a tool (the client) and a language smartness provider (the server) to integrate features like auto complete, go to definition, find all references and alike into the tool
#+end_quote

-- [[https://microsoft.github.io/language-server-protocol/specifications/specification-current/][official Language Server Protocol specification]]

Take a look at [[https://langserver.org/][langserver.org]]

#+begin_src emacs-lisp
(use-package lsp-mode
  :ensure t
  :init
  ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
  (setq lsp-keymap-prefix "C-c l")
  :hook ((lsp-mode . lsp-enable-which-key-integration)
         (bash-ts-mode . lsp)
         (lsp-mode . lsp-ui-mode)
         (lsp-mode . sideline-mode)
         )
  :commands (lsp lsp-deferred)
  :config
  (setq lsp-enable-snippet nil)
  (lsp-enable-which-key-integration t)
  (general-evil-define-key 'insert lsp-mode-map
    "C-." 'company-capf
    )
  :custom
  ;; general stuff
  (lsp-eldoc-render-all t)
  (lsp-idle-delay 0.6)
  ;; enable / disable the hints as you prefer:
  (lsp-inlay-hint-enable t)
  ;; rust
  ;; what to use when checking on-save. "check" is default, I prefer clippy
  (lsp-rust-analyzer-cargo-watch-command "clippy")
  ;; These are optional configurations. See https://emacs-lsp.github.io/lsp-mode/page/lsp-rust-analyzer/#lsp-rust-analyzer-display-chaining-hints for a full list
  (lsp-rust-analyzer-display-lifetime-elision-hints-enable "skip_trivial")
  (lsp-rust-analyzer-display-chaining-hints t)
  (lsp-rust-analyzer-display-lifetime-elision-hints-use-parameter-names nil)
  (lsp-rust-analyzer-display-closure-return-type-hints t)
  (lsp-rust-analyzer-display-parameter-hints nil)
  (lsp-rust-analyzer-display-reborrow-hints nil)
  :general
  (proton/leader-keys
    "c" '(:ignore t :wk "Code")
    "c c" '(compile :wk "Compile")
    "c r" '(lsp-rename :wk "Rename")
    "c f" '(lsp-format-region :wk "Format region")
    "c F" '(lsp-format-buffer :wk "Format buffer")
    )
  )

;; force lsp-mode to forget the workspace folders for multi root servers so the workspace folders are added on demand
(advice-add 'lsp
            :before (lambda (&rest _args)
                      (eval '(setf (lsp-session-server-id->folders (lsp-session)) (ht))))
            )

;; The path to lsp-mode needs to be added to load-path as well as the
;; path to the `clients' subdirectory.
(add-to-list 'load-path (expand-file-name "lib/lsp-mode" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "lib/lsp-mode/clients" user-emacs-directory))

(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]\\.venv\\'")
  (defun proton/lsp-ignore-semgrep-rulesRefreshed (workspace notification)
    "Ignore semgrep/rulesRefreshed notification."
    (when (equal (gethash "method" notification) "semgrep/rulesRefreshed")
      (lsp--info "Ignored semgrep/rulesRefreshed notification")
      t)) ;; Return t to indicate the notification is handled

  (advice-add 'lsp--on-notification :before-until #'proton/lsp-ignore-semgrep-rulesRefreshed)
  )
#+end_src

** LSP-UI

#+begin_src emacs-lisp
(use-package lsp-ui
  :ensure t
  :commands lsp-ui-mode
  :bind (:map lsp-ui-mode-map
              ("C-c d" . lsp-ui-doc-toggle)
              ("M-j" . lsp-ui-imenu)
              )
  :custom
  (lsp-ui-peek-always-show t)
  (lsp-ui-sideline-show-hover t)
  (lsp-ui-doc-enable nil)
  :general
  (proton/leader-keys
    "c d" '(lsp-ui-doc-show :wk "Document that")
    "c D" '(lsp-ui-doc-hide :wk "Close doc")
    )
  :config
  (setq lsp-ui-doc-position 'at-point
        lsp-ui-sideline-enable nil)
  (general-define-key
   :keymaps 'lsp-mode-map
   [remap lsp-find-definitions] 'lsp-ui-peek-find-definitions
   [remap lsp-find-references] 'lsp-ui-peek-find-references
   )
  )
#+end_src


** Sideline LSP

#+begin_src emacs-lisp
(use-package sideline-lsp
  :init
  (setq sideline-backends-right '(sideline-lsp)))
#+end_src

** Ansible

Development of emacs ansible module has moved to [[https://gitlab.com/emacs-ansible/emacs-ansible][gitlab]].
Due to the latest changes, encrypt and decrypt using a password file no longer seems to work.
Take a look at the issues [[https://gitlab.com/emacs-ansible/emacs-ansible/-/issues/2][2]] and [[https://gitlab.com/emacs-ansible/emacs-ansible/-/issues/3][3]].

#+begin_src emacs-lisp
(use-package ansible
  :ensure t
  :hook ((yaml-ts-mode . ansible-mode)
         (ansible . ansible-auto-decrypt-encrypt))
  :config
  (setq ansible-section-face 'font-lock-variable-name-face
        ansible-task-label-face 'font-lock-doc-face
        ansible-vault-password-file nil)
  )
(use-package ansible-doc
  :ensure t
  )
(use-package jinja2-mode
  :ensure t
  :mode "\\.j2$"
  )

(use-package yaml-mode
  :ensure t
  :hook (
         (yaml-ts-mode . lsp-deferred)
         (yaml-ts-mode . company-mode)
         (yaml-ts-mode . whitespace-mode)
         )
  )
#+end_src

** Python

#+begin_src emacs-lisp
(use-package python
  :ensure nil
  :hook ((python-ts-mode . lsp-deferred))
  )
#+end_src

** Terraform

Use the official terraform language server from hashicorp.
The server should be installed using the playbook =playbooks/languageserver.yml=

#+begin_src emacs-lisp
(use-package terraform-mode
  :ensure t
  :hook ((terraform-mode . lsp-deferred))
  :custom (terraform-indent-level 2)
  :config
  (setq lsp-terraform-ls-server (format "%s/.local/bin/terraform-ls" (getenv "HOME")))
  )
#+end_src

** Rust

#+begin_src emacs-lisp
(use-package rustic
  :ensure t
  :custom
  (rustic-analyzer-command '("rustup" "run" "stable" "rust-analyzer"))
  :bind (:map rustic-mode-map
              ("M-j" . lsp-ui-imenu)
              ("M-?" . lsp-find-references)
              ("C-c C-c l" . flycheck-list-errors)
              ("C-c C-c a" . lsp-execute-code-action)
              ("C-c C-c r" . lsp-rename)
              ("C-c C-c q" . lsp-workspace-restart)
              ("C-c C-c Q" . lsp-workspace-shutdown)
              ("C-c C-c s" . lsp-rust-analyzer-status))
  :hook ((rustic-mode . proton/rustic-mode-hook))
  :config
  ;; uncomment for less flashiness
  ;; (setq lsp-eldoc-hook nil)
  ;; (setq lsp-enable-symbol-highlighting nil)
  ;; (setq lsp-signature-auto-activate nil)

  ;; comment to disable rustfmt on save
  (setq rustic-format-on-save t)
  )

(defun proton/rustic-mode-hook ()
  ;; so that run C-c C-c C-r works without having to confirm, but don't try to
  ;; save rust buffers that are not file visiting. Once
  ;; https://github.com/brotzeit/rustic/issues/253 has been resolved this should
  ;; no longer be necessary.
  (when buffer-file-name
    (setq-local buffer-save-without-query t))
  (add-hook 'before-save-hook 'lsp-format-buffer nil t)
  )
#+end_src

* Perspective Mode

#+begin_src emacs-lisp
(use-package perspective
  :ensure t
  :custom
  (persp-mode-prefix-key (kbd "C-<tab>"))
  (persp-sort 'created)
  (doom-modeline-display-default-persp-name t)
  :init
  (persp-mode)
  :config
  (proton/leader-keys
    "TAB" '(:ignore t :wk "Perspective")
    "TAB r" '(persp-rename :wk "Rename perspective")
    "TAB s" '(persp-switch :wk "Create/Switch perspective")
    "TAB n" '(persp-next :wk "Next perspective")
    "TAB p" '(persp-prev :wk "Previous perspective")
    "TAB q" '(proton/persp-kill-current :wk "Kill perspective")
    "TAB k" '(persp-remove-buffer :wk "Remove buffer from perspective")
    "TAB a" '(persp-add-buffer :wk "Add buffer to perspective")
    "TAB A" '(persp-set-buffer :wk "Set buffer to perspective")

    "TAB 1" '((lambda () (interactive) (persp-switch-by-number 1)) :wk "Switch to perspective 1")
    "TAB 2" '((lambda () (interactive) (persp-switch-by-number 2)) :wk "Switch to perspective 2")
    "TAB 3" '((lambda () (interactive) (persp-switch-by-number 3)) :wk "Switch to perspective 3")
    "TAB 4" '((lambda () (interactive) (persp-switch-by-number 4)) :wk "Switch to perspective 4")
    "TAB 5" '((lambda () (interactive) (persp-switch-by-number 5)) :wk "Switch to perspective 5")
    "TAB 6" '((lambda () (interactive) (persp-switch-by-number 6)) :wk "Switch to perspective 6")
    "TAB 7" '((lambda () (interactive) (persp-switch-by-number 7)) :wk "Switch to perspective 7")
    "TAB 8" '((lambda () (interactive) (persp-switch-by-number 8)) :wk "Switch to perspective 8")
    "TAB 9" '((lambda () (interactive) (persp-switch-by-number 9)) :wk "Switch to perspective 9")
    "TAB 0" '((lambda () (interactive) (persp-switch-by-number 10)) :wk "Switch to perspective 10")
    )
  )

(defun proton/persp-kill-current()
  "Kill the current active perspective"
  (interactive)
  (persp-kill (persp-current-name))
  )
#+end_src

* Perspective/Projectile

Integrate =perspective.el= with =projectile= so that opened projects get their own perspective.

Take a look at the [[https://github.com/bbatsov/persp-projectile][Github]] project.

#+begin_src emacs-lisp
(use-package persp-projectile
  :ensure t
  :init
  (proton/leader-keys
    "p p" '(projectile-persp-switch-project :wk "Switch project"))
  )
#+end_src

* Shell

The terminal emulator of choice is =wezterm=, =zsh= the shell and =oh-my-zsh= the framework.
The prompt is =starship.rs=.

** Eshell

Reasons to give eshell a chance:

#+begin_quote
- No need for pagers like less. You won't ever re-run a long-output command by appending | less to it.
- Little need for output filtering (the sed, grep, awk black-magic): output the result to an Emacs buffer, use some Lisp functions, use Evil ex commands, iedit, helm-moccur or multiple-cursors...
- Eshell supports TRAMP! Which means you don't have to put aside your powerful environment when switching to root or connecting to a remote host: all the power of your Emacs can be used anywhere, the shell included.
#+end_quote

Taken from [[https://www.reddit.com/r/emacs/comments/6y3q4k/yes_eshell_is_my_main_shell][reddit - Yes, Eshell is my main shell]].

#+begin_src emacs-lisp
(use-package eshell-syntax-highlighting
  :ensure t
  :after esh-mode
  :config
  (eshell-syntax-highlighting-global-mode +1)
  )
(setq eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-destroy-buffer-when-process-dies t
      eshell-visual-commands'("bash" "btm" "htop" "ssh" "top" "zsh"))
#+end_src

* Templates

#+begin_src emacs-lisp
;; Configure Tempel
(use-package tempel
  :ensure t
  ;; Require trigger prefix before template name when completing.
  ;; :custom
  ;; (tempel-trigger-prefix "<")
  :init

  ;; Setup completion at point
  (defun tempel-setup-capf ()
    ;; Add the Tempel Capf to `completion-at-point-functions'.
    ;; `tempel-expand' only triggers on exact matches. Alternatively use
    ;; `tempel-complete' if you want to see all matches, but then you
    ;; should also configure `tempel-trigger-prefix', such that Tempel
    ;; does not trigger too often when you don't expect it. NOTE: We add
    ;; `tempel-expand' *before* the main programming mode Capf, such
    ;; that it will be tried first.
    (setq-local completion-at-point-functions
                (cons #'tempel-expand
                      completion-at-point-functions)))

  (add-hook 'org-mode-hook 'tempel-setup-capf)
  (add-hook 'conf-mode-hook 'tempel-setup-capf)
  (add-hook 'prog-mode-hook 'tempel-setup-capf)
  (add-hook 'text-mode-hook 'tempel-setup-capf)

  ;; Optionally make the Tempel templates available to Abbrev,
  ;; either locally or globally. `expand-abbrev' is bound to C-x '.
  ;; (add-hook 'prog-mode-hook #'tempel-abbrev-mode)
  ;; (global-tempel-abbrev-mode)
  :config

  (proton/leader-keys
   "t" '(:ignore t :wk "Templates")
   "t c" '(tempel-complete :wk "Complete")
   "t i" '(tempel-insert :wk "Insert")
   "t d" '(tempel-done :wk "Done")
   "t n" '(tempel-next :wk "Next")
   )
)

;; Optional: Add tempel-collection.
;; The package is young and doesn't have comprehensive coverage.
(use-package tempel-collection
  :ensure t
  :after tempel
  )
#+end_src

* Tldr

Show some quick help if man pages are too long.

#+begin_src emacs-lisp
(use-package tldr
  :ensure t
  :config
  (proton/leader-keys
    "s t" '(tldr :wk "Lookup tldr for command help"))
  )
#+end_src

Run the source block to execute tldr from the shell
#+begin_src sh :results output :var CMD=(read-string "Command: ")
tldr $CMD
#+end_src

* Transparency

Add transparent background for emacs windows.
This requires emacs >= 29.

#+begin_src emacs-lisp
;; (add-to-list 'default-frame-alist '(alpha-background . 95)) 
#+end_src

* Treemacs

Open treemacs either using =M-x treemacs= or =LEADER o t=.
Use =o= to toggle the open action for a node in treemacs.
=o o= simply opens the node.
=o |= splits the window left/right (|).
=o -= splits the window top/bottom (-).
This may be counter intuitive, because evil splits vertical in left/right.

#+begin_src emacs-lisp
(use-package treemacs
  :ensure t
  :defer t
  :bind
  (:map treemacs-mode-map
        ("o -" . treemacs-visit-node-vertical-split)
        ("o |" . treemacs-visit-node-horizontal-split)
        )
  :general
  (proton/leader-keys
    "o t" '(treemacs :wk "Treemacs file tree"))
  :config
  (setq treemacs-width 40
        )
  )

(use-package treemacs-evil
  :after (treemacs evil)
  :ensure t)

(use-package treemacs-projectile
  :after (treemacs projectile)
  :ensure t)

(use-package treemacs-magit
  :after (treemacs magit)
  :ensure t)

(use-package treemacs-perspective
  :after (treemacs perspective)
  :ensure t
  :config (treemacs-set-scope-type 'Perspectives))
#+end_src

* Tree Sitter

Take a look at the [[https://tree-sitter.github.io/tree-sitter/#parsers][tree-sitter parsers list]].

#+begin_src emacs-lisp
(setq treesit-language-source-alist
   '((bash "https://github.com/tree-sitter/tree-sitter-bash")
     (css "https://github.com/tree-sitter/tree-sitter-css")
     (dockerfile "https://github.com/camdencheek/tree-sitter-dockerfile")
     (elisp "https://github.com/Wilfred/tree-sitter-elisp")
     (html "https://github.com/tree-sitter/tree-sitter-html")
     (javascript "https://github.com/tree-sitter/tree-sitter-javascript")
     (json "https://github.com/tree-sitter/tree-sitter-json")
     (make "https://github.com/alemuller/tree-sitter-make")
     (markdown "https://github.com/ikatyang/tree-sitter-markdown")
     (org "https://github.com/milisims/tree-sitter-org")
     (python "https://github.com/tree-sitter/tree-sitter-python")
     (rust "https://github.com/tree-sitter/tree-sitter-rust")
     (sql "https://github.com/m-novikov/tree-sitter-sql")
     (toml "https://github.com/tree-sitter/tree-sitter-toml")
     (yaml "https://github.com/ikatyang/tree-sitter-yaml")
     ))

(dolist (lang treesit-language-source-alist)
  (unless (treesit-language-available-p (car lang))
    (treesit-install-language-grammar (car lang))))

(dolist (mapping
         '((bash-mode . bash-ts-mode)
           (css-mode . css-ts-mode)
           (html-mode . html-ts-mode)
           (json-mode . json-ts-mode)
           (makefile-mode . makefile-ts-mode)
           (python-mode . python-ts-mode)
           (yaml-mode . yaml-ts-mode)))
  (add-to-list 'major-mode-remap-alist mapping))
#+end_src

** Auto tree sitter

#+begin_src emacs-lisp
(use-package treesit-auto
  :ensure t
  :custom
  (treesit-auto-install 'prompt)
  :config
  (setq my-rust-tsauto-config
      (make-treesit-auto-recipe
       :lang 'rust
       :ts-mode 'rustic-mode
       :remap '(rust-mode rust-ts-mode)
       :ext "\\.rs\\'")
      )
  (treesit-auto-add-to-auto-mode-alist 'all)
  (add-to-list 'treesit-auto-recipe-list my-rust-tsauto-config)
  (global-treesit-auto-mode))
#+end_src

** Folding

At the time of writing ts-fold [[https://github.com/emacs-tree-sitter/ts-fold/issues/48][does not work using emacs >= 29]] with built-in tree-sitter.
There is a fork by [[https://github.com/abougouffa/treesit-fold][abougouffa]].
Will see how the discussion will go on, as folding could be very need for large json, yml, xml documents.

#+begin_src emacs-lisp
;; (use-package ts-fold
;;   :ensure (:host github :repo "emacs-tree-sitter/ts-fold")
;;   :config
;;   (global-ts-fold-mode)
;;   )

;; (use-package ts-fold-indicators
;;   :ensure (:host github :repo "emacs-tree-sitter/ts-fold")
;;   :config
;;   (global-ts-fold-indicators-mode)
;;   )
#+end_src

So at the moment =hideshow= is the choice to get folding to work.

#+begin_src emacs-lisp
(use-package hideshow
  :ensure nil
  :commands (hs-toggle-hiding
             hs-hide-block
             hs-show-block
             hs-hide-level
             hs-show-all
             hs-hide-all)
  :config
  (defun proton/ensure-hideshow (&rest _)
    ;; Enable hideshow if it is not already active
    (unless (bound-and-true-p hs-minor-mode)
      (hs-minor-mode +1)))

  (defun proton/nxml-forward-element ()
    (let ((nxml-sexp-element-flag))
      (setq nxml-sexp-element-flag (not (looking-at "<!--")))
      (unless (looking-at outline-regexp)
        (condition-case nil
            (nxml-forward-balanced-item 1)
          (error nil)))))

  (add-to-list 'hs-special-modes-alist '(yaml-ts-mode "\\s-*\\_<\\(?:[^:]+\\)\\_>"
                         ""
                         "#"
                         nil nil))
  (add-to-list 'hs-special-modes-alist '(json-ts-mode "[[{]" "[]}]"))
  (add-to-list 'hs-special-modes-alist
        '(nxml-mode
          "<!--\\|<[^/>]>\\|<[^/][^>]*[^/]>"
          ""
          "<!--" ;; won't work on its own; uses syntax table
          (lambda (arg) (proton/nxml-forward-element))
          nil))

  (dolist (cmd '(hs-toggle-hiding
                 hs-hide-block
                 hs-show-block
                 hs-hide-level
                 hs-show-all
                 hs-hide-all))
    (advice-add cmd :before #'proton/ensure-hideshow))
  )
#+end_src

* Sudo Edit

#+begin_src emacs-lisp
(use-package sudo-edit
  :ensure t
  :config
  (proton/leader-keys
    "f u" '(sudo-edit-find-file :wk "Sudo find file")
    "f U" '(sudo-edit :wk "Sudo edit file")
  )
)
#+end_src

* Which key

#+begin_src emacs-lisp

(use-package which-key
  :ensure t
  :init
  (which-key-mode)
  :diminish
  :config
  (setq which-key-side-window-location 'bottom
    which-key-sort-order #'which-key-key-order-alpha
    which-key-sort-uppercase-first nil
    which-key-min-display-lines 6
    which-key-side-window-max-height 0.25
    which-key-idle-delay 0.3
    which-key-separator "  ")
  )
#+end_src

* Inheritenv

#+begin_src emacs-lisp
(use-package inheritenv
  :ensure t
  )
#+end_src

* Direnv

#+begin_quote
direnv is an extension for your shell. It augments existing shells with a new feature that can load and unload environment variables depending on the current directory.
#+end_quote

-- [[https://direnv.net][direnv.net]]

#+begin_src emacs-lisp
(use-package envrc
  :ensure t
  :config
  (envrc-global-mode)
  )
#+end_src
