---
- ansible.builtin.import_playbook: ../playbooks/path.yml
- ansible.builtin.import_playbook: ../playbooks/yay.yml
- ansible.builtin.import_playbook: ../playbooks/dotfiles.yml
- ansible.builtin.import_playbook: ../playbooks/fonts.yml
- ansible.builtin.import_playbook: ../playbooks/aliases.yml
- ansible.builtin.import_playbook: ../playbooks/ghostty.yml
- ansible.builtin.import_playbook: ../playbooks/git.yml
- ansible.builtin.import_playbook: ../playbooks/curl.yml
- ansible.builtin.import_playbook: ../playbooks/vscode.yml
- ansible.builtin.import_playbook: ../playbooks/neovim.yml
- ansible.builtin.import_playbook: ../playbooks/helix-editor.yml
- ansible.builtin.import_playbook: ../playbooks/fzf.yml
- ansible.builtin.import_playbook: ../playbooks/borg.yml
- ansible.builtin.import_playbook: ../playbooks/python.yml
- ansible.builtin.import_playbook: ../playbooks/asdfvm.yml
- ansible.builtin.import_playbook: ../playbooks/direnv.yml
- ansible.builtin.import_playbook: ../playbooks/arandr.yml
- ansible.builtin.import_playbook: ../playbooks/X.yml
- ansible.builtin.import_playbook: ../playbooks/network.yml
- ansible.builtin.import_playbook: ../playbooks/ssh_unlock.yml
- ansible.builtin.import_playbook: ../playbooks/fido2.yml
- ansible.builtin.import_playbook: ../playbooks/bluetooth.yml
- ansible.builtin.import_playbook: ../playbooks/bat.yml
- ansible.builtin.import_playbook: ../playbooks/eza.yml
- ansible.builtin.import_playbook: ../playbooks/duf.yml
- ansible.builtin.import_playbook: ../playbooks/rust.yml
- ansible.builtin.import_playbook: ../playbooks/shfmt.yml
- ansible.builtin.import_playbook: ../playbooks/leftwm.yml
- ansible.builtin.import_playbook: ../playbooks/picom.yml
- ansible.builtin.import_playbook: ../playbooks/rofi.yml
- ansible.builtin.import_playbook: ../playbooks/gnome_keyring.yml
- ansible.builtin.import_playbook: ../playbooks/minikube.yml
- ansible.builtin.import_playbook: ../playbooks/autorandr.yml
- ansible.builtin.import_playbook: ../playbooks/magic-wormhole.yml
- ansible.builtin.import_playbook: ../playbooks/goss.yml
- ansible.builtin.import_playbook: ../playbooks/dive.yml
- ansible.builtin.import_playbook: ../playbooks/redshift.yml
- ansible.builtin.import_playbook: ../playbooks/dust.yml
- ansible.builtin.import_playbook: ../playbooks/wireguard.yml
- ansible.builtin.import_playbook: ../playbooks/pandoc.yml
- ansible.builtin.import_playbook: ../playbooks/tldr.yml
- ansible.builtin.import_playbook: ../playbooks/ocr.yml
- ansible.builtin.import_playbook: ../playbooks/docker.yml
- ansible.builtin.import_playbook: ../playbooks/openapi.yml
- ansible.builtin.import_playbook: ../playbooks/zoxide.yml
- ansible.builtin.import_playbook: ../playbooks/whois.yml
- ansible.builtin.import_playbook: ../playbooks/nerdctl.yml
- ansible.builtin.import_playbook: ../playbooks/yazi.yml
- ansible.builtin.import_playbook: ../playbooks/lazygit.yml
- ansible.builtin.import_playbook: ../playbooks/opentofu.yml
- ansible.builtin.import_playbook: ../playbooks/just.yml
- ansible.builtin.import_playbook: ../playbooks/hyprland.yml
- ansible.builtin.import_playbook: ../playbooks/wofi.yml
- ansible.builtin.import_playbook: ../playbooks/fx.yml
- ansible.builtin.import_playbook: ../playbooks/grype.yml

- ansible.builtin.import_playbook: ../playbooks/kde.yml
- ansible.builtin.import_playbook: ../playbooks/emacs.yml
- ansible.builtin.import_playbook: ../playbooks/chromium.yml
- ansible.builtin.import_playbook: ../playbooks/brave-browser.yml
- ansible.builtin.import_playbook: ../playbooks/qutebrowser.yml
- ansible.builtin.import_playbook: ../playbooks/keepassxc.yml
- ansible.builtin.import_playbook: ../playbooks/okular.yml
- ansible.builtin.import_playbook: ../playbooks/thunderbird.yml
- ansible.builtin.import_playbook: ../playbooks/inkscape.yml
- ansible.builtin.import_playbook: ../playbooks/vlc.yml
- ansible.builtin.import_playbook: ../playbooks/wallpaper.yml
- ansible.builtin.import_playbook: ../playbooks/rclone.yml
- ansible.builtin.import_playbook: ../playbooks/veracrypt.yml
- ansible.builtin.import_playbook: ../playbooks/virtualization.yml
- ansible.builtin.import_playbook: ../playbooks/pidgin.yml
- ansible.builtin.import_playbook: ../playbooks/httpie.yml
- ansible.builtin.import_playbook: ../playbooks/kanri.yml
- ansible.builtin.import_playbook: ../playbooks/zen-browser.yml
- ansible.builtin.import_playbook: ../playbooks/localsend.yml
