---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    conf: "{{ home }}/.config/alacritty/alacritty.yml"

  tasks:
    - name: Install alacritty
      community.general.pacman:
        name: alacritty
        state: present

    - name: Create alacritty config directory
      ansible.builtin.file:
        path: "{{ home }}/.config/alacritty"
        state: directory
        mode: 0750

    - name: Gather alacritty conf stats
      ansible.builtin.stat:
        path: "{{ conf }}"
      register: conf_stat

    - name: Remove alacritty configuration if the default created
      ansible.builtin.file:
        path: "{{ conf }}"
        state: absent
      when: conf_stat.stat.isreg is defined and conf_stat.stat.isreg

    - name: Link configuration file alacritty.yml
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/alacritty/alacritty.yml"
        path: "{{ home }}/.config/alacritty/alacritty.yml"
        state: link
