---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    aliases_path: "{{ home }}/.aliases"

  tasks:
    - name: Create ~/.aliases
      ansible.builtin.file:
        path: "{{ aliases_path }}"
        mode: 0640
        state: file

    - name: Set all configured aliases
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias {{ item.name }}='{{ item.value }}'"
        state: present
      loop: "{{ aliases }}"
