---
- name: " [ ALIASES ]"
  hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    aliases_path: "{{ home }}/.aliases"

  tasks:

    - name: Set all configured aliases
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias {{ item.name }}='{{ item.value }}'"
        state: present
        create: true
        mode: "0640"
      loop: "{{ aliases }}"
