---
- name: "[ ASDF-VM ]"
  hosts: all

  vars:
    asdf_home: "{{ lookup('env', 'HOME') }}/.asdf"
    asdf_version: 0.20.2
    asdf_checksum: sha256:6d45e6fab12f50a259b5643adf06a2e77af30a87300b4402440eda09af467a6d
    asdf_target_arch: linux-amd64

  tasks:
    - name: Download asdf binary
      ansible.builtin.get_url:
        url: "https://github.com/asdf-vm/asdf/releases/download/v{{ asdf_version }}/asdf-v{{ asdf_version }}-{{ asdf_target_arch }}.tar.gz"
        checksum: "{{ asdf_checksum }}"
        dest: /tmp/asdf.tar.gz
        mode: "0644"

    - name: Unarchive binary
      ansible.builtin.unarchive:
        src: /tmp/asdf.tar.gz
        dest: "{{ home }}/.local/bin"
        include:
          - asdf
