---
- hosts: all
  tasks:
    - name: Check if asdf-vm is already installed
      ansible.builtin.stat:
        path: "{{ lookup('env', 'HOME') }}/.asdf"
      register: asdfvm

    - name: Clone the asdf-vm repo
      git:
        repo: git@github.com/asdf-vm/asdf.git
        branch: v0.9.0
      when: not asdfvm.stat.exists

    
