---
- name: "[ ASDF-VM ]"
  hosts: all

  vars:
    asdf_home: "{{ lookup('env', 'HOME') }}/.asdf"

  tasks:
    - name: Check if asdf-vm is already installed
      ansible.builtin.stat:
        path: "{{ asdf_home }}"
      register: asdfvm

    - name: Clone the asdf-vm repo
      ansible.builtin.git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "{{ asdf_home }}"
        version: v0.10.2
      when: not asdfvm.stat.exists
