---
- name: "[ BAT ]"
  hosts: all

  vars:
    aliases_path: "{{ lookup('env', 'HOME') }}/.aliases"

  tasks:
    - name: Install bat (cat replacement)
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - bat
        - bat-extras

    - name: Set the bat alias for cat
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias cat='bat'"
