---
- name: "[ BORG ]"
  hosts: all

  vars:
    default_includes:
      - /home
      - /etc
      - /var
    default_excludes:
      - /home/*/cache/*
      - /var/tmp/*
    default_repo:
      - /mnt/backup/borg

  tasks:
    - name: Install borg
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - borg
        - python-llfuse

    - name: Set default repo
      ansible.builtin.set_fact:
        local_borg_repo: default_repo
      when: local_borg_repo is not defined

    - name: Set default includes
      ansible.builtin.set_fact:
        local_borg_includes: default_includes
      when: local_borg_includes is not defined

    - name: Set default excludes
      ansible.builtin.set_fact:
        local_borg_excludes: default_excludes
      when: local_borg_excludes is not defined

    - name: Copy borg automated backup script
      ansible.builtin.template:
        src: ../borg/borg-mate.sh.tmpl.j2
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/borg-mate"
        mode: "0755"
      when:
        - borg_repo is defined
        - borg_includes is defined and borg_includes is sequence
