---
- hosts: all

  tasks:
    - name: Install borg
      become: true
      ansible.builtin.pacman:
        name: borg
        state: present

    - name: Copy borg automated backup script
      ansible.builtin.template:
        src: ../borg/borg-mate.sh.tmpl.j2
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/borg-mate"
        mode: 0755
      when:
        - borg_repo is defined
        - borg_includes is defined and borg_includes is sequence
