---
- name: "[ DOCKER ]"
  become: true
  hosts: all

  tasks:

    - name: Ensure docker is present
      become: true
      community.general.pacman:
        name:
          - docker
          - docker-compose
          - docker-buildx
        state: present

    - name: Docker should not be started by default
      ansible.builtin.systemd_service:
        name: docker.service
        state: stopped
        enabled: false

    - name: Current user should be in the docker group
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: true
