---
- name: "[ DOCKER CREDENTIAL SECRETSERVICE ]"
  hosts: all

  vars:
    _dcs_version: "{{ dcs_version | default('0.9.8') }}"
    _dcs_checksum: "{{ dcs_checksum | default('sha256:052a0243588b231fde8009f7fe95afc6f536e9d20f6b5896dfd5bc8fd55852f2') }}"
    _dcs_os_architecture: "{{ dcs_os_architecture | default('linux-amd64') }}"
    _dcs_default_url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ _dcs_version }}/docker-credential-secretservice-v{{ _dcs_version }}.{{ _dcs_os_architecture }}"
    _dcs_url: "{{ dcs_url | default(_dcs_default_url) }}"
    _dcs_default_binary_dest: "{{ home }}/.local/bin/docker-credential-secretservice"
    _dcs_binary_dest: "{{ dcs_binary_dest | default(_dcs_default_binary_dest) }}"

  tasks:

    - name: Download docker credential secretservice
      ansible.builtin.get_url:
        url: "{{ _dcs_url }}"
        checksum: "{{ _dcs_checksum }}"
        mode: "0750"
        dest: "{{ _dcs_binary_dest }}"
