---
- name: Deploy dotfiles
  hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    dotfiles_path: "{{ home }}/dotfiles"

  tasks:
    - name: See if dotfiles exists
      ansible.builtin.stat:
        path: "{{ dotfiles_path }}"
      register: dotfiles_exists

    # PACKAGE INSTALLATION
    - name: Install necessary packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: ["zsh", "curl"]
    # END PACKAGE INSTALLATION

    # OH MY ZSH
    - name: Check oh my zsh installation
      ansible.builtin.stat:
        path: "{{ home }}/.oh-my-zsh"
      register: omz_home

    - block:
        - name: Download oh-my-zsh install script
          ansible.builtin.get_url:
            dest: ./install.sh
            mode: 0750
            url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh

        - name: Install oh my zsh
          ansible.builtin.command:
            cmd: sh install.sh --unattended

        - name: Remove ~/.zshrc
          ansible.builtin.file:
            path: "{{ home }}/.zshrc"
            state: absent

        - name: Remove downloaded install.sh
          ansible.builtin.file:
            path: ./install.sh
            state: absent
      when: not omz_home.stat.exists
    # END OH MY ZSH

    # ZSH THEME
    - name: Get powerlevel10k theme
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        depth: 1
        dest: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"
        version: master
    # END ZSH THEME

    # ZSH USER PLUGINS
    - name: Get zsh-users plugins
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/{{ item }}.git"
        dest: "{{ home }}/.oh-my-zsh/custom/plugins/{{ item }}"
        version: master
      loop:
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - zsh-completions

    # END ZSH USER PLUGINS

    # CONFIGURATION LINKS
    - name: Link configuration files
      ansible.builtin.file:
        state: link
        src: "{{ item.src }}"
        path: "{{ item.path }}"
      loop:
        - src: "{{ home }}/dotfiles/zshrc"
          path: "{{ home }}/.zshrc"
        - src: "{{ home }}/dotfiles/zsh"
          path: "{{ home }}/.zsh"
        - src: "{{ home }}/dotfiles/gitconfig"
          path: "{{ home }}/.gitconfig"
        - src: "{{ home }}/dotfiles/zsh/configs/p10k.zsh"
          path: "{{ home }}/.p10k.zsh"
    # END CONFIGURATION LINKS


    # SHELL CONFIGURATION
    - name: Set zsh as shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        shell: /bin/zsh
    # END SHELL CONFIGURATION

