---
- name: Deploy dotfiles
  hosts: all

  vars:
    # Customize these if you want to
    dotfiles_path: "{{ ansible_env.HOME }}/dotfiles"

    # Necessary for a system that uses gui terminal applications
    # These fonts must be set inside the terminal app, which is a
    # setting that this playbook does NOT cover
    install_custom_font: true
    font_download_path: "{{ ansible_env.HOME }}/.fonts"

    # Change only in case the url changed
    font_base_url: https://github.com/romkatv/powerlevel10k-media/raw/master
    font_files:
      - "MesloLGS NF Regular.ttf"
      - "MesloLGS NF Bold.ttf"
      - "MesloLGS NF Italic.ttf"
      - "MesloLGS NF Bold Italic.ttf"
    home: "{{ lookup('env', 'HOME') }}"
  
  handlers:
    - name: install you complete me
      command:
        cmd: 'python install.py'
        chdir: "{{ ansible_env.HOME }}/.vim/bundle/YouCompleteMe"

  tasks:
    - name: See if dotfiles exists
      stat:
        path: "{{ dotfiles_path }}"
      register: dotfiles_exists

    # PACKAGE INSTALLATION
    - name: Install necessary packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop: ["cmake", "gcc", "vim", "zsh", "curl"]
    # END PACKAGE INSTALLATION

    # OH MY ZSH
    - name: Check oh my zsh installation
      ansible.builtin.stat:
        path: "{{ home }}/.oh-my-zsh"
      register: omz_home

    - name: Install oh my zsh
      command:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not omz_home.stat.exists
      register: omz_install
    # END OH MY ZSH

    # ZSH THEME
    - name: Get powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        depth: 1
        dest: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"
        version: master
    # END ZSH THEME

    # ZSH USER PLUGINS
    - name: Get zsh-users plugins
      git:
        repo: "git@github.com:zsh-users/{{ item }}.git"
        dest: "{{ home }}/.oh-my-zsh/custom/plugins/{{ item }}"
        version: master
      loop:
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-completions

    # END ZSH USER PLUGINS

    # CONFIGURATION LINKS
    - name: Link configuration files
      file:
        state: link
        src: "{{ item.src }}"
        path: "{{ item.path }}"
      loop:
      - src: "{{ home }}/dotfiles/vimrc"
        path: "{{ home }}/.vimrc"
      - src: "{{ home }}/dotfiles/zshrc"
        path: "{{ home }}/.zshrc"
      - src: "{{ home }}/dotfiles/zsh"
        path: "{{ home }}/.zsh"
      - src: "{{ home }}/dotfiles/vim/bundle.vim"
        path: "{{ home }}/.vimrc.bundles"
      - src: "{{ home }}/dotfiles/vim/map.vim"
        path: "{{ home }}/.vimrc.map"
      - src: "{{ home }}/dotfiles/gitconfig"
        path: "{{ home }}/.gitconfig"
      - src: "{{ home }}/dotfiles/zsh/configs/p10k.zsh"
        path: "{{ home }}/.p10k.zsh"
    # END CONFIGURATION LINKS

    # VIM PLUGINS
    - name: Install vim plugins
      command:
        cmd: "vim -u {{ home }}/.vimrc.bundles +PluginInstall +qall"
    # END VIM PLUGINS


    # SHELL CONFIGURATION
    - name: Set zsh as shell
      become: true
      user:
        name: "{{ ansible_env.USER }}"
        shell: /bin/zsh
    # END SHELL CONFIGURATION

    # FONT INSTALLATION
    - name: Install custom fonts
      block:
        - name: Create download folder
          file:
            path: "{{ font_download_path }}"
            mode: 0755
            state: directory

        - name: Download the files
          get_url:
            url: "{{ font_base_url }}/{{ item | urlencode() }}"
            dest: "{{ font_download_path }}/{{ item }}"
          loop: "{{ font_files }}"
      when: install_custom_font
    # END FONT INSTALLATION
