---
- name: Deploy dotfiles
  hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    default_zsh_custom: "{{ home }}/.oh-my-zsh/custom"
    zsh_custom: "{{ lookup('env', 'ZSH_CUSTOM') | default(default_zsh_custom, true) }}"
    dotfiles_path: "{{ home }}/dotfiles"
    aliases_path: "{{ lookup('env', 'HOME') }}/.aliases"


  tasks:
    - name: See if dotfiles exists
      ansible.builtin.stat:
        path: "{{ dotfiles_path }}"
      register: dotfiles_exists

    # PACKAGE INSTALLATION
    - name: Install necessary packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: ["zsh", "curl"]
    # END PACKAGE INSTALLATION

    # OH MY ZSH
    - name: Check oh my zsh installation
      ansible.builtin.stat:
        path: "{{ home }}/.oh-my-zsh"
      register: omz_home

    - name: Enable oh-my-zsh
      when: not omz_home.stat.exists
      block:
        - name: Download oh-my-zsh install script
          ansible.builtin.get_url:
            dest: ./install.sh
            mode: "0750"
            url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh

        - name: Install oh my zsh
          ansible.builtin.command:
            cmd: sh install.sh --unattended
          changed_when: true

        - name: Remove ~/.zshrc
          ansible.builtin.file:
            path: "{{ home }}/.zshrc"
            state: absent

        - name: Remove downloaded install.sh
          ansible.builtin.file:
            path: ./install.sh
            state: absent
    # END OH MY ZSH

    # ZSH THEMES
    - name: Get powerlevel10k theme
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        depth: 1
        dest: "{{ zsh_custom }}/themes/powerlevel10k"
        version: master
    # END ZSH THEMES

    # ZSH USER PLUGINS
    - name: Get zsh-users plugins
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/{{ item }}.git"
        dest: "{{ home }}/.oh-my-zsh/custom/plugins/{{ item }}"
        version: master
      loop:
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - zsh-completions
    # END ZSH USER PLUGINS

    # CONFIGURATION LINKS
    - name: Link configuration files
      ansible.builtin.file:
        state: link
        src: "{{ item.src }}"
        path: "{{ item.path }}"
      loop:
        - src: "{{ home }}/dotfiles/zshrc"
          path: "{{ home }}/.zshrc"
        - src: "{{ home }}/dotfiles/zsh"
          path: "{{ home }}/.zsh"
        - src: "{{ home }}/dotfiles/gitconfig"
          path: "{{ home }}/.gitconfig"
        - src: "{{ home }}/dotfiles/zsh/configs/p10k.zsh"
          path: "{{ home }}/.p10k.zsh"
    # END CONFIGURATION LINKS

    # STARSHIP PROMPT
    - name: Ensure starship is installed
      become: true
      community.general.pacman:
        name: starship
        state: present

    - name: Link starship configuration
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/starship/starship.toml"
        dest: "{{ home }}/.config/starship.toml"
        state: link
    # END STARSHIP PROMPT

    # SHELL CONFIGURATION
    - name: Set zsh as shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        shell: /bin/zsh
    # END SHELL CONFIGURATION

    - name: Ensure zprofile is present
      ansible.builtin.file:
        path: "{{ home }}/.zprofile"
        state: touch
        mode: "0640"

    - name: Add some aliases
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias {{ item.alias }}=\"{{ item.cmd }}\""
      loop:
        - alias: sshl
          cmd: grep -P \"^Host ([^*]+)$\" $HOME/.ssh/config | sed 's/Host //' | sort
