---
- name: Install and configure duf (df replacement)
  hosts: all

  vars:
    aliases_path: "{{ lookup('env', 'HOME') }}/.aliases"

  tasks:
    - name: Install duf
      become: true
      community.general.pacman:
        name: duf
        state: present

    - name: Set the duf alias for df
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias df='duf --hide-fs tmpfs,vfat'"
