---
- hosts: all

  vars:
    dxvk_dir: "{{ lookup('env', 'HOME') }}/.dxvk"
    dxvk_version: "v1.10.2"
    dxvk_build_dir: "{{ lutris_dir }}/runtime/dxvk"
    lutris_dir: "{{ lookup('env', 'HOME') }}/.local/share/lutris"

  tasks:

    - name: Install required packages
      become: true
      ansible.builtin.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - meson
        - mingw-w64-gcc
        - mingw-w64-headers
        - glslang

    - name: Clone dxvk repo
      ansible.builtin.git:
        repo: git@github.com:doitsujin/dxvk.git
        dest: "{{ dxvk_dir }}"
        version: "{{ dxvk_version }}"

    - name: Stats of lutris dir
      ansible.builtin.stat:
        path: "{{ dxvk_build_dir }}/dxvk-{{ dxvk_version }}"
      register: lutris

    - name: Build dxvk
      ansible.builtin.command:
        cmd: "./package-release.sh {{ dxvk_version }} {{ dxvk_build_dir }} --no-package"
        chdir: "{{ dxvk_dir }}"
      when: not lutris.stat.exists
