---
- name: "[ DXVK AUR]"
  hosts: all

  tasks:
    - name: Install dxvk from aur
      become: true
      become_user: "{{ aur_builder_user }}"
      kewlfft.aur.aur:
        name: dxvk-bin
        state: present
        use: "{{ aur_helper }}"
