---
- hosts: all

  vars:
    dxvk_dir: "{{ lookup('env', 'HOME') }}/.dxvk"
    dxvk_build_dir: "{{ dxvk_dir }}/target"
    dxvk_version: "master"

  handlers:
    - name: Build dxvk
      ansible.builtin.command:
        cmd: "./package-release.sh {{ dxvk_version }} {{ dxvk_build_dir }} --no-package"
        chdir: "{{ dxvk_dir }}"


  tasks:

    - name: Install required packages
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - meson
        - mingw-w64-gcc
        - mingw-w64-headers
        - glslang

    - name: Load dxvk repo contents
      ansible.builtin.git:
        repo: git@github.com:doitsujin/dxvk.git
        dest: "{{ dxvk_dir }}"
        version: "{{ dxvk_version }}"
      notify: Build dxvk
