---
- name: Install and configure doom emacs
  hosts: all
  gather_facts: false

  vars:
    emacsd: "{{ home }}/.config/emacs.d/doom"
    chemacs2d: "{{ home }}/.emacs.d"
    envvars: "{{ emacsd }}/.local/env"
    doomdir: "{{ home }}/dotfiles/emacs"

  handlers:
    - name: Install doom emacs
      ansible.builtin.command:
        cmd: "{{ emacsd }}/bin/doom install"

  tasks:
    - name: Ensure emacs and doom required software is installed
      become: true
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - emacs-nativecomp
        - ripgrep
        - findutils
        - fd
        - maim
        - libvterm
        - shellcheck  # required for module sh
        - prettier  # requires for module json, yaml ...

    - name: Check for emacs.d directory
      ansible.builtin.stat:
        path: "{{ emacsd }}"
      register: emacs_repo

    - name: Clone doom emacs
      ansible.builtin.git:
        repo: https://github.com/doomemacs/doomemacs
        dest: "{{ emacsd }}"
        version: master
      when: emacs_repo.stat.isdir is not defined or not emacs_repo.stat.isdir
      # doom install must be executed by hand because of a bug
      # that native compiling packages hangs cause
      # of missing user input
      # https://github.com/doomemacs/doomemacs/issues/5592
      # notify: Install doom emacs

    - name: Export emacs.d/bin to path
      ansible.builtin.lineinfile:
        path: "{{ path_file_path }}"
        line: "export PATH={{ emacsd }}/bin:$PATH"

    - name: Set DOOMDIR environment variable
      ansible.builtin.lineinfile:
        path: "{{ home }}/.zprofile"
        line: 'export DOOMDIR="{{ doomdir }}"'

    - name: Check for emacs custom configuration
      ansible.builtin.stat:
        path: "{{ home }}/dotfiles/emacs/local.el"
      register: emacs_local

    - name: Ensure ansible is set correctly in the .dir-locals.el
      ansible.builtin.blockinfile:
        path: "{{ home }}/dotfiles/.dir-locals.el"
        create: true
        mode: 0640
        state: present
        marker: ";; {mark} ANSIBLE MANAGED BLOCK"
        block: |
          ((yaml-mode . ((lsp-ansible-ansible-path . "{{ home }}/dotfiles/.venv/bin/ansible")
                         (lsp-ansible-ansible-lint-path . "{{ home }}/dotfiles/.venv/bin/ansible-lint")
                         (lsp-ansible-python-interpreter-path . "{{ home }}/dotfiles/.venv/bin/python"))))

    - name: Generate envvars file
      ansible.builtin.command:
        cmd: "{{ emacsd }}/bin/doom env -o {{ envvars }}"
      changed_when: true

    - name: Get chemacs2
      ansible.builtin.git:
        repo: https://github.com/plexus/chemacs2
        dest: "{{ home }}/.emacs.d"
        version: main

    - name: Build ~/.emacs-profiles.el
      ansible.builtin.copy:
        mode: 0644
        dest: "{{ home }}/.emacs-profiles.el"
        content: |
          (("default" . ((user-emacs-directory   . "{{ emacsd }}")
                         (env . (("DOOMDIR"      . "{{ doomdir }}")))))
          )
