---
- hosts: all
  gather_facts: false

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    emacsd: "{{ home }}/.emacs.d"
    doomd: "{{ home }}/.doom.d"
    envvars: "{{ emacsd }}/.local/env"

  handlers:
    - name: install doom emacs
      ansible.builtin.command:
        cmd: "{{ emacsd }}/bin/doom install"

  tasks:
    - name: Ensure emacs and doom required software is installed
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - emacs-nativecomp
        - ripgrep
        - findutils
        - fd
        - maim
        - libvterm
        - shellcheck  # required for module sh
        - prettier  # requires for module json, yaml ...

    - name: Check for emacs.d directory
      ansible.builtin.stat:
        path: "{{ emacsd }}"
      register: emacs_repo

    - name: Clone doom emacs
      ansible.builtin.git:
        repo: https://github.com/doomemacs/doomemacs
        dest: "{{ emacsd }}"
        version: master
      when: emacs_repo.stat.isdir is not defined or not emacs_repo.stat.isdir
      # doom install must be executed by hand because of a bug
      # that native compiling packages hangs cause
      # of missing user input
      # https://github.com/doomemacs/doomemacs/issues/5592
      # notify: install doom emacs

    - name: Export emacs.d/bin to path
      ansible.builtin.lineinfile:
        path: "{{ path_file_path }}"
        line: "export PATH={{ emacsd }}/bin:$PATH"

    - name: Ensure ~/.doom.d exists
      ansible.builtin.file:
        path: "{{ doomd }}"
        state: directory
        mode: 0755

    - name: Link doom configuration files
      ansible.builtin.file:
        path: "{{ item.dest }}/{{ item.linkname }}"
        src: "{{ item.src }}"
        state: link
      loop:
        - src: "{{ home }}/dotfiles/emacs/init.el"
          dest: "{{ doomd }}"
          linkname: "init.el"
        - src: "{{ home }}/dotfiles/emacs/packages.el"
          dest: "{{ doomd }}"
          linkname: "packages.el"
        - src: "{{ home }}/dotfiles/emacs/config.el"
          dest: "{{ doomd }}"
          linkname: "config.el"
        - src: "{{ home }}/dotfiles/emacs/elfeed.org"
          dest: "{{ home }}/Org"
          linkname: "elfeed.org"

    - name: Check for emacs custom configuration
      ansible.builtin.stat:
        path: "{{ home }}/dotfiles/emacs/local.el"
      register: emacs_local

    - name: Link custom emacs configuration
      ansible.builtin.file:
        path: "{{ doomd }}/local.el"
        src: "{{ emacs_local.stat.path }}"
        state: link
      when: emacs_local.stat.isreg is defined and emacs_local.stat.isreg

    - name: Ensure ansible is set correctly in the .dir-locals.el
      ansible.builtin.blockinfile:
        path: "{{ home }}/dotfiles/.dir-locals.el"
        create: true
        mode: 0640
        state: present
        marker: ";; {mark} ANSIBLE MANAGED BLOCK"
        block: |
          ((yaml-mode . ((lsp-ansible-ansible-path . "{{ home }}/dotfiles/.venv/bin/ansible")
                         (lsp-ansible-ansible-lint-path . "{{ home }}/dotfiles/.venv/bin/ansible-lint")
                         (lsp-ansible-python-interpreter-path . "{{ home }}/dotfiles/.venv/bin/python"))))

    - name: Generate envvars file
      ansible.builtin.command:
        cmd: "{{ emacsd }}/bin/doom env -o {{ envvars }}"
      changed_when: true
