---
- name: "[ EMACS ]"
  hosts: all
  gather_facts: false

  vars:
    emacsd_doom: "{{ home }}/.config/emacs.d/doom"
    emacsd_spacemacs: "{{ home }}/.config/emacs.d/spacemacs"
    emacsd_vanillamacs: "{{ home }}/.config/emacs.d/vanillamacs"
    chemacs2d: "{{ home }}/.emacs.d"
    envvars: "{{ emacsd_doom }}/.local/env"
    doomdir: "{{ home }}/dotfiles/emacs"
    spacemacsdir: "{{ home }}/dotfiles/spacemacs"
    vanillamacsdir: "{{ home }}/dotfiles/vanillamacs"

  handlers:
    - name: Install doom emacs
      ansible.builtin.command:
        cmd: "{{ emacsd_doom }}/bin/doom install"
      changed_when: true

  tasks:
    - name: Ensure emacs and doom required software is installed
      become: true
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - emacs-nativecomp
        - cmake
        - ripgrep
        - findutils
        - fd
        - maim
        - libvterm
        - shellcheck  # required for module sh
        - prettier  # required for module json, yaml ...
        - python-grip  # required for markdown +grip
        - the_silver_searcher
        - ack

    - name: Check for emacs.d directory
      ansible.builtin.stat:
        path: "{{ emacsd_doom }}"
      register: emacs_repo

    - name: Clone doom emacs
      ansible.builtin.git:
        repo: https://github.com/doomemacs/doomemacs
        dest: "{{ emacsd_doom }}"
        version: master
      when: emacs_repo.stat.isdir is not defined or not emacs_repo.stat.isdir
      # doom install must be executed by hand because of a bug
      # that native compiling packages hangs cause
      # of missing user input
      # https://github.com/doomemacs/doomemacs/issues/5592
      # notify: Install doom emacs

    - name: Export emacs.d/bin to path
      ansible.builtin.lineinfile:
        path: "{{ path_file_path }}"
        line: "export PATH={{ emacsd_doom }}/bin:$PATH"

    - name: Set emacs environment variables
      ansible.builtin.lineinfile:
        path: "{{ home }}/.zprofile"
        line: 'export {{ item.key }}="{{ item.value }}"'
      loop:
        - key: DOOMDIR
          value: "{{ doomdir }}"
        - key: SPACEMACSDIR
          value: "{{ spacemacsdir }}"
        - key: VANILLAMACSDIR
          value: "{{ vanillamacsdir }}"

    - name: Check for emacs custom configuration
      ansible.builtin.stat:
        path: "{{ home }}/dotfiles/emacs/local.el"
      register: emacs_local

    - name: Ensure ansible is set correctly in the .dir-locals.el
      ansible.builtin.blockinfile:
        path: "{{ home }}/dotfiles/.dir-locals.el"
        create: true
        mode: "0640"
        state: present
        marker: ";; {mark} ANSIBLE MANAGED BLOCK"
        block: |
          ((yaml-mode . ((lsp-ansible-ansible-path . "{{ home }}/dotfiles/.venv/bin/ansible")
                         (lsp-ansible-ansible-lint-path . "{{ home }}/dotfiles/.venv/bin/ansible-lint")
                         (lsp-ansible-python-interpreter-path . "{{ home }}/dotfiles/.venv/bin/python"))))

    - name: Generate envvars file
      ansible.builtin.command:
        cmd: "{{ emacsd_doom }}/bin/doom env -o {{ envvars }}"
      changed_when: true

    - name: Get chemacs2
      ansible.builtin.git:
        repo: https://github.com/plexus/chemacs2
        dest: "{{ home }}/.emacs.d"
        version: main

    - name: Build ~/.emacs-profiles.el
      ansible.builtin.copy:
        mode: "0644"
        dest: "{{ home }}/.emacs-profiles.el"
        content: |
          (("default" . ((user-emacs-directory   . "{{ emacsd_doom }}")))
            ("doom"        . ((user-emacs-directory     . "{{ emacsd_doom }}")
                              (env . (("DOOMDIR"        . "{{ doomdir }}")))))
            ("spacemacs"   . ((user-emacs-directory     . "{{ emacsd_spacemacs }}")
                              (env . (("SPACEMACSDIR"   . "{{ spacemacsdir }}")))))
            ("vanillamacs" . ((user-emacs-directory     . "{{ emacsd_vanillamacs }}")
                              (env . (("VANILLAMACSDIR" . "{{ vanillamacsdir }}")))))
          )

    - name: Ensure vanillamacs user-emacs-directory exists
      ansible.builtin.file:
        path: "{{ emacsd_vanillamacs }}"
        state: directory
        mode: "750"

    - name: Ensure vanillamacs early-init.el is linked
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/vanillamacs/{{ item }}"
        dest: "{{ emacsd_vanillamacs }}/{{ item }}"
        state: link
      loop:
        - early-init.el
        - init.el
