---
- name: "[ EMACS ]"
  hosts: all
  gather_facts: false

  vars:
    emacsd_doom: "{{ home }}/.config/emacs.d/doom"
    emacsd_vanillamacs: "{{ home }}/.config/emacs.d/vanillamacs"
    envvars: "{{ emacsd_doom }}/.local/env"
    doomdir: "{{ home }}/dotfiles/emacs"
    vanillamacsdir: "{{ home }}/dotfiles/vanillamacs"

  handlers:
    - name: Install doom emacs
      ansible.builtin.command:
        cmd: "{{ emacsd_doom }}/bin/doom install"
      changed_when: true

  tasks:
    - name: Ensure emacs and doom required software is installed
      become: true
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - emacs
        - cmake
        - ripgrep
        - findutils
        - fd
        - maim
        - libvterm
        - shellcheck  # required for module sh
        - prettier  # required for module json, yaml ...
        - python-grip  # required for markdown +grip
        - the_silver_searcher

    - name: Check for emacs.d directory
      ansible.builtin.stat:
        path: "{{ emacsd_doom }}"
      register: emacs_repo

    - name: Clone doom emacs
      ansible.builtin.git:
        repo: https://github.com/doomemacs/doomemacs
        dest: "{{ emacsd_doom }}"
        version: master
      when: emacs_repo.stat.isdir is not defined or not emacs_repo.stat.isdir
      # doom install must be executed by hand because of a bug
      # that native compiling packages hangs cause
      # of missing user input
      # https://github.com/doomemacs/doomemacs/issues/5592
      # notify: Install doom emacs

    - name: Export emacs.d/bin to path
      ansible.builtin.lineinfile:
        path: "{{ path_file_path }}"
        line: "export PATH={{ emacsd_doom }}/bin:$PATH"

    - name: Set emacs environment variables
      ansible.builtin.lineinfile:
        path: "{{ home }}/.zprofile"
        line: 'export {{ item.key }}="{{ item.value }}"'
        state: absent
      loop:
        - key: DOOMDIR
          value: "{{ doomdir }}"
        - key: VANILLAMACSDIR
          value: "{{ vanillamacsdir }}"

    - name: Check for emacs custom configuration
      ansible.builtin.stat:
        path: "{{ home }}/dotfiles/emacs/local.el"
      register: emacs_local

    - name: Ensure ansible is set correctly in the .dir-locals.el
      ansible.builtin.blockinfile:
        path: "{{ home }}/dotfiles/.dir-locals.el"
        create: true
        mode: "0640"
        state: present
        marker: ";; {mark} ANSIBLE MANAGED BLOCK"
        block: |
          ((yaml-mode . ((lsp-ansible-ansible-path . "{{ home }}/dotfiles/.venv/bin/ansible")
                         (lsp-ansible-ansible-lint-path . "{{ home }}/dotfiles/.venv/bin/ansible-lint")
                         (lsp-ansible-python-interpreter-path . "{{ home }}/dotfiles/.venv/bin/python"))))

    - name: Generate envvars file
      ansible.builtin.command:
        cmd: "{{ emacsd_doom }}/bin/doom env -o {{ envvars }}"
      changed_when: true

    - name: Remove chemacs2 if present
      ansible.builtin.file:
        path: "{{ home }}/.emacs.d"
        state: absent

    - name: Build emacs desktop files
      ansible.builtin.template:
        src: "../templates/emacs.desktop.j2"
        dest: "{{ home }}/.local/share/applications/{{ item.desktop_filename }}.desktop"
        mode: "0644"
      loop:
        - user_emacs_dir: "{{ emacsd_doom }}"
          config_dir: "{{ doomdir }}"
          env_key: "DOOMDIR"
          name: "Doom emacs"
          desktop_filename: doom_emacs
        - user_emacs_dir: "{{ emacsd_vanillamacs }}"
          config_dir: "{{ vanillamacsdir }}"
          env_key: "VANILLAMACSDIR"
          name: Vanillamacs
          desktop_filename: vanillamacs

    - name: Build ~/.emacs-profiles.el
      ansible.builtin.file:
        path: "{{ home }}/.emacs-profiles.el"
        state: absent

    - name: Ensure vanillamacs user-emacs-directory exists
      ansible.builtin.file:
        path: "{{ emacsd_vanillamacs }}"
        state: directory
        mode: "750"

    - name: Copy emacs icons
      ansible.builtin.copy:
        src: "{{ home }}/dotfiles/vanillamacs/emacs.png"
        dest: "{{ home }}/.icons/emacs.png"
        mode: "0644"

    - name: Ensure vanillamacs early-init.el is linked
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/vanillamacs/{{ item }}"
        dest: "{{ emacsd_vanillamacs }}/{{ item }}"
        state: link
      loop:
        - early-init.el
        - init.el
