---
- name: "[ EZA ]"
  hosts: all

  vars:
    aliases_path: "{{ lookup('env', 'HOME') }}/.aliases"

  tasks:
    - name: Install eza (ls replacement)
      become: true
      community.general.pacman:
        name: eza
        state: present

    - name: Set the exa alias for ls
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias ls='eza -hg'"
