---
- name: "[ EZA ]"
  hosts: all

  vars:
    aliases_path: "{{ lookup('env', 'HOME') }}/.aliases"

  tasks:
    - name: Install eza (ls replacement)
      become: true
      community.general.pacman:
        name: eza
        state: present

    - name: Set the eza alias for ls
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias {{ item.alias }}='{{ item.value }}'"
      loop:
        - alias: ls
          value: eza
        - alias: ll
          value: eza -lhg
        - alias: la
          value: eza -lhga
        - alias: lt
          value: eza -hgT
