- name: "[ FELIX-RS ]"
  hosts: all

  tasks:
    - name: Install felix file manager
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - felix-rs
        - zathura
        - chafa

    - name: Ensure felix config dir exists
      ansible.builtin.file:
        path: "{{ home }}/.config/felix"
        state: directory
        mode: "0755"

    - name: Configure felix
      ansible.builtin.template:
        src: ../templates/felix-rs.yml.j2
        dest: "{{ home }}/.config/felix/config.yml"
        mode: "0640"
