---
- name: Install and configure local firewall
  hosts: all

  handlers:
    - name: Start ufw
      become: true
      ansible.builtin.service:
        name: ufw
        enabled: true
        state: started

  tasks:
    - name: Ensure required packages are present
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - ufw
        - gufw
      notify:
        - Start ufw
