---
- name: Install and configure local firewall
  hosts: all

  handlers:
    - name: Start firewalld
      become: true
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

  tasks:
    - name: Ensure required packages are present
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - firewalld
      notify:
        - Start firewalld
