---
- name: Install nerd fonts
  hosts: all

  handlers:
    - name: Run fc-cache
      ansible.builtin.command: fc-cache -v -f
      changed_when: true

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    font_download_path: "{{ home }}/.local/share/fonts"
    repo_fonts:
      - ttf-jetbrains-mono-nerd
      - ttf-cascadia-code-nerd
      - ttf-fira-sans

    # Change only in case the url changed
    fonts:
      - font_base_url: https://github.com/FAlthausen/Vollkorn-Typeface/raw/master/fonts/ttf
        font_files:
          - "Vollkorn-Black.ttf"
          - "Vollkorn-BlackItalic.ttf"
          - "Vollkorn-Bold.ttf"
          - "Vollkorn-BoldItalic.ttf"
          - "Vollkorn-ExtraBold.ttf"
          - "Vollkorn-ExtraBoldItalic.ttf"
          - "Vollkorn-Italic.ttf"
          - "Vollkorn-Medium.ttf"
          - "Vollkorn-MediumItalic.ttf"
          - "Vollkorn-Regular.ttf"
          - "Vollkorn-SemiBold.ttf"
          - "Vollkorn-SemiBoldItalic.ttf"
      - font_base_url: https://github.com/domtronn/all-the-icons.el/raw/master/fonts
        font_files:
          - "all-the-icons.ttf"
          - "file-icons.ttf"
          - "fontawesome.ttf"
          - "material-design-icons.ttf"
          - "octicons.ttf"
          - "weathericons.ttf"

  tasks:
    - name: Create font download folder
      ansible.builtin.file:
        path: "{{ font_download_path }}"
        mode: "0755"
        state: directory

    - name: Download the files
      ansible.builtin.get_url:
        url: "{{ item.0.font_base_url }}/{{ item.1 | urlencode() }}"
        dest: "{{ font_download_path }}/{{ item.1 }}"
        mode: "0644"
      loop: "{{ fonts | subelements('font_files') }}"
      loop_control:
        label: "{{ item.1 }}"
      notify: Run fc-cache

    - name: Install fonts from manjaro/arch repos
      become: true
      community.general.pacman:
        name: "{{ repo_fonts }}"
        state: present
      notify: Run fc-cache
