---
- name: Install nerd fonts
  hosts: all

  handlers:
    - name: run fc-cache
      ansible.builtin.command: fc-cache

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    font_download_path: "{{ home }}/.local/share/fonts"

    fonts_nerd_font_root: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts
    fonts_nerd_fonts:
      # JetBrains Mono including ligatures
      - path: JetBrainsMono/Ligatures/Bold/complete/JetBrains%20Mono%20Bold%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Bold Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/BoldItalic/complete/JetBrains%20Mono%20Bold%20Italic%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Bold Italic Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/ExtraBold/complete/JetBrains%20Mono%20ExtraBold%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono ExtraBold Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/ExtraBoldItalic/complete/JetBrains%20Mono%20ExtraBold%20Italic%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono ExtraBold Italic Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/ExtraLight/complete/JetBrains%20Mono%20ExtraLight%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono ExtraLight Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/ExtraLightItalic/complete/JetBrains%20Mono%20ExtraLight%20Italic%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono ExtraLight Italic Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/Italic/complete/JetBrains%20Mono%20Italic%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Italic Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/Light/complete/JetBrains%20Mono%20Light%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Light Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/LightItalic/complete/JetBrains%20Mono%20Light%20Italic%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Light Italic Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/Medium/complete/JetBrains%20Mono%20Medium%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Medium Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/MediumItalic/complete/JetBrains%20Mono%20Medium%20Italic%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Medium Italic Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Regular Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/SemiBold/complete/JetBrains%20Mono%20SemiBold%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono SemiBold Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/SemiBoldItalic/complete/JetBrains%20Mono%20SemiBold%20Italic%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono SemiBold Italic Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/Thin/complete/JetBrains%20Mono%20Thin%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Thin Nerd Font Complete.ttf
      - path: JetBrainsMono/Ligatures/ThinItalic/complete/JetBrains%20Mono%20Thin%20Italic%20Nerd%20Font%20Complete.ttf
        filename: JetBrains Mono Thin Italic Nerd Font Complete.ttf
      # Meslo LG with large, medium and small line gap
      - path: Meslo/L/Bold-Italic/complete/Meslo%20LG%20L%20Bold%20Italic%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG L Bold Italic Nerd Font Complete.ttf
      - path: Meslo/L/Bold/complete/Meslo%20LG%20L%20Bold%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG L Bold Nerd Font Complete.ttf
      - path: Meslo/L/Italic/complete/Meslo%20LG%20L%20Italic%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG L Italic Nerd Font Complete.ttf
      - path: Meslo/L/Regular/complete/Meslo%20LG%20L%20Regular%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG L Regular Nerd Font Complete.ttf
      - path: Meslo/M/Bold-Italic/complete/Meslo%20LG%20M%20Bold%20Italic%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG M Bold Italic Nerd Font Complete.ttf
      - path: Meslo/M/Bold/complete/Meslo%20LG%20M%20Bold%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG M Bold Nerd Font Complete.ttf
      - path: Meslo/M/Italic/complete/Meslo%20LG%20M%20Italic%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG M Italic Nerd Font Complete.ttf
      - path: Meslo/M/Regular/complete/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG M Regular Nerd Font Complete.ttf
      - path: Meslo/S/Bold-Italic/complete/Meslo%20LG%20S%20Bold%20Italic%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG S Bold Italic Nerd Font Complete.ttf
      - path: Meslo/S/Bold/complete/Meslo%20LG%20S%20Bold%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG S Bold Nerd Font Complete.ttf
      - path: Meslo/S/Italic/complete/Meslo%20LG%20S%20Italic%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG S Italic Nerd Font Complete.ttf
      - path: Meslo/S/Regular/complete/Meslo%20LG%20S%20Regular%20Nerd%20Font%20Complete.ttf
        filename: Meslo LG S Regular Nerd Font Complete.ttf
      - path: OpenDyslexic/Regular/complete/OpenDyslexic%20Regular%20Nerd%20Font%20Complete.otf
        filename: OpenDyslexic Regular Nerd Font Complete.otf

    # Change only in case the url changed
    fonts:
      - font_base_url: https://github.com/bBoxType/FiraSans/raw/master/Fira_Sans_4_3/Fonts/Fira_Sans_TTF_4301/Normal/Roman
        font_files:
          - "FiraSans-Bold.ttf"
          - "FiraSans-Book.ttf"
          - "FiraSans-Eight.ttf"
          - "FiraSans-ExtraBold.ttf"
          - "FiraSans-ExtraLight.ttf"
          - "FiraSans-Four.ttf"
          - "FiraSans-Hair.ttf"
          - "FiraSans-Heavy.ttf"
          - "FiraSans-Light.ttf"
          - "FiraSans-Medium.ttf"
          - "FiraSans-Regular.ttf"
          - "FiraSans-SemiBold.ttf"
          - "FiraSans-Thin.ttf"
          - "FiraSans-Two.ttf"
          - "FiraSans-Ultra.ttf"
          - "FiraSans-UltraLight.ttf"
      - font_base_url: https://github.com/bBoxType/FiraSans/raw/master/Fira_Sans_4_3/Fonts/Fira_Sans_TTF_4301/Normal/Italic
        font_files:
          - "FiraSans-BoldItalic.ttf"
          - "FiraSans-BookItalic.ttf"
          - "FiraSans-EightItalic.ttf"
          - "FiraSans-ExtraBoldItalic.ttf"
          - "FiraSans-ExtraLightItalic.ttf"
          - "FiraSans-FourItalic.ttf"
          - "FiraSans-HairItalic.ttf"
          - "FiraSans-HeavyItalic.ttf"
          - "FiraSans-Italic.ttf"
          - "FiraSans-LightItalic.ttf"
          - "FiraSans-MediumItalic.ttf"
          - "FiraSans-SemiBoldItalic.ttf"
          - "FiraSans-ThinItalic.ttf"
          - "FiraSans-TwoItalic.ttf"
          - "FiraSans-UltraItalic.ttf"
          - "FiraSans-UltraLightItalic.ttf"
      - font_base_url: https://github.com/FAlthausen/Vollkorn-Typeface/raw/master/fonts/ttf
        font_files:
          - "Vollkorn-Black.ttf"
          - "Vollkorn-BlackItalic.ttf"
          - "Vollkorn-Bold.ttf"
          - "Vollkorn-BoldItalic.ttf"
          - "Vollkorn-ExtraBold.ttf"
          - "Vollkorn-ExtraBoldItalic.ttf"
          - "Vollkorn-Italic.ttf"
          - "Vollkorn-Medium.ttf"
          - "Vollkorn-MediumItalic.ttf"
          - "Vollkorn-Regular.ttf"
          - "Vollkorn-SemiBold.ttf"
          - "Vollkorn-SemiBoldItalic.ttf"

  tasks:
    - name: Create font download folder
      ansible.builtin.file:
        path: "{{ font_download_path }}"
        mode: 0755
        state: directory

    - name: Download the files
      ansible.builtin.get_url:
        url: "{{ item.0.font_base_url }}/{{ item.1 | urlencode() }}"
        dest: "{{ font_download_path }}/{{ item.1 }}"
        mode: 0644
      loop: "{{ fonts | subelements('font_files') }}"
      loop_control:
        label: "{{ item.1 }}"
      notify: run fc-cache

    - name: Install nerd fonts
      ansible.builtin.get_url:
        url: "{{ fonts_nerd_font_root }}/{{ item.path }}"
        dest: "{{ font_download_path }}/{{ item.filename }}"
        mode: 0644
      loop: "{{ fonts_nerd_fonts }}"
      notify: run fc-cache
      tags: ["nerd"]
