---
- name: Install nerd fonts
  hosts: all

  handlers:
    - name: run fc-cache
      ansible.builtin.command: fc-cache

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    font_download_path: "{{ home }}/.local/share/fonts"

    fonts_nerd_font_root: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts
    fonts_nerd_fonts:
      # JetBrains Mono including ligatures
      - path: JetBrainsMono/Ligatures/Bold/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Bold.ttf
        filename: JetBrains Mono Nerd Font Complete Bold.ttf
      - path: JetBrainsMono/Ligatures/BoldItalic/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Bold%20Italic.ttf
        filename: JetBrains Mono Nerd Font Complete Bold Italic.ttf
      - path: JetBrainsMono/Ligatures/ExtraBold/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20ExtraBold.ttf
        filename: JetBrains Mono Nerd Font Complete ExtraBold.ttf
      - path: JetBrainsMono/Ligatures/ExtraBoldItalic/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20ExtraBold%20Italic.ttf
        filename: JetBrains Mono Nerd Font Complete ExtraBold Italic.ttf
      - path: JetBrainsMono/Ligatures/ExtraLight/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20ExtraLight.ttf
        filename: JetBrains Mono Nerd Font Complete ExtraLight.ttf
      - path: JetBrainsMono/Ligatures/ExtraLightItalic/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20ExtraLight%20Italic.ttf
        filename: JetBrains Mono Nerd Font Complete ExtraLight Italic.ttf
      - path: JetBrainsMono/Ligatures/Italic/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Italic.ttf
        filename: JetBrains Mono Nerd Font Complete Italic.ttf
      - path: JetBrainsMono/Ligatures/Light/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Light.ttf
        filename: JetBrains Mono Nerd Font Complete Light.ttf
      - path: JetBrainsMono/Ligatures/LightItalic/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Light%20Italic.ttf
        filename: JetBrains Mono Nerd Font Complete Light Italic.ttf
      - path: JetBrainsMono/Ligatures/Medium/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Medium.ttf
        filename: JetBrains Mono Nerd Font Complete Medium.ttf
      - path: JetBrainsMono/Ligatures/MediumItalic/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Medium%20Italic.ttf
        filename: JetBrains Mono Nerd Font Complete Medium Italic.ttf
      - path: JetBrainsMono/Ligatures/Regular/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Regular.ttf
        filename: JetBrains Mono Nerd Font Complete Regular.ttf
      - path: JetBrainsMono/Ligatures/SemiBold/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20SemiBold.ttf
        filename: JetBrains Mono Nerd Font Complete SemiBold.ttf
      - path: JetBrainsMono/Ligatures/SemiBoldItalic/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20SemiBold%20Italic.ttf
        filename: JetBrains Mono Nerd Font Complete SemiBold Italic.ttf
      - path: JetBrainsMono/Ligatures/Thin/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Thin.ttf
        filename: JetBrains Mono Nerd Font Complete Thin.ttf
      - path: JetBrainsMono/Ligatures/ThinItalic/complete/JetBrains%20Mono%20Nerd%20Font%20Complete%20Thin%20Italic.ttf
        filename: JetBrains Mono Nerd Font Complete Thin Italic.ttf
      # dont be confused by the name
      - path: CascadiaCode/Regular/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Regular.otf
        filename: Caskaydia Cove Nerd Font Complete Regular.otf

    # Change only in case the url changed
    fonts:
      - font_base_url: https://github.com/bBoxType/FiraSans/raw/master/Fira_Sans_4_3/Fonts/Fira_Sans_TTF_4301/Normal/Roman
        font_files:
          - "FiraSans-Bold.ttf"
          - "FiraSans-Book.ttf"
          - "FiraSans-Eight.ttf"
          - "FiraSans-ExtraBold.ttf"
          - "FiraSans-ExtraLight.ttf"
          - "FiraSans-Four.ttf"
          - "FiraSans-Hair.ttf"
          - "FiraSans-Heavy.ttf"
          - "FiraSans-Light.ttf"
          - "FiraSans-Medium.ttf"
          - "FiraSans-Regular.ttf"
          - "FiraSans-SemiBold.ttf"
          - "FiraSans-Thin.ttf"
          - "FiraSans-Two.ttf"
          - "FiraSans-Ultra.ttf"
          - "FiraSans-UltraLight.ttf"
      - font_base_url: https://github.com/bBoxType/FiraSans/raw/master/Fira_Sans_4_3/Fonts/Fira_Sans_TTF_4301/Normal/Italic
        font_files:
          - "FiraSans-BoldItalic.ttf"
          - "FiraSans-BookItalic.ttf"
          - "FiraSans-EightItalic.ttf"
          - "FiraSans-ExtraBoldItalic.ttf"
          - "FiraSans-ExtraLightItalic.ttf"
          - "FiraSans-FourItalic.ttf"
          - "FiraSans-HairItalic.ttf"
          - "FiraSans-HeavyItalic.ttf"
          - "FiraSans-Italic.ttf"
          - "FiraSans-LightItalic.ttf"
          - "FiraSans-MediumItalic.ttf"
          - "FiraSans-SemiBoldItalic.ttf"
          - "FiraSans-ThinItalic.ttf"
          - "FiraSans-TwoItalic.ttf"
          - "FiraSans-UltraItalic.ttf"
          - "FiraSans-UltraLightItalic.ttf"
      - font_base_url: https://github.com/FAlthausen/Vollkorn-Typeface/raw/master/fonts/ttf
        font_files:
          - "Vollkorn-Black.ttf"
          - "Vollkorn-BlackItalic.ttf"
          - "Vollkorn-Bold.ttf"
          - "Vollkorn-BoldItalic.ttf"
          - "Vollkorn-ExtraBold.ttf"
          - "Vollkorn-ExtraBoldItalic.ttf"
          - "Vollkorn-Italic.ttf"
          - "Vollkorn-Medium.ttf"
          - "Vollkorn-MediumItalic.ttf"
          - "Vollkorn-Regular.ttf"
          - "Vollkorn-SemiBold.ttf"
          - "Vollkorn-SemiBoldItalic.ttf"

  tasks:
    - name: Create font download folder
      ansible.builtin.file:
        path: "{{ font_download_path }}"
        mode: 0755
        state: directory

    - name: Download the files
      ansible.builtin.get_url:
        url: "{{ item.0.font_base_url }}/{{ item.1 | urlencode() }}"
        dest: "{{ font_download_path }}/{{ item.1 }}"
        mode: 0644
      loop: "{{ fonts | subelements('font_files') }}"
      loop_control:
        label: "{{ item.1 }}"
      notify: run fc-cache

    - name: Install nerd fonts
      ansible.builtin.get_url:
        url: "{{ fonts_nerd_font_root }}/{{ item.path }}"
        dest: "{{ font_download_path }}/{{ item.filename }}"
        mode: 0644
      loop: "{{ fonts_nerd_fonts }}"
      notify: run fc-cache
      tags: ["nerd"]
