---
- name: "[ GIT ]"
  hosts: all

  tasks:
    - name: Install git
      become: true
      community.general.pacman:
        name:
          - git
          - git-delta
        state: present

    - name: Link gitconfig
      ansible.builtin.file:
        state: link
        src: "{{ home }}/dotfiles/gitconfig"
        path: "{{ home }}/.gitconfig"
