---
- name: "[ GNOME KEYRING ]"
  hosts: all

  tasks:
    - name: Ensure required packages are present
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - gnome-keyring
        - seahorse

    - name: Disable gcr-ssh-agent
      ansible.builtin.systemd_service:
        name: gcr-ssh-agent
        scope: user
        state: stopped
        enabled: false

    - name: Disable and mask gcr-ssh-agent.socket
      become: true
      ansible.builtin.systemd_service:
        name: gcr-ssh-agent.socket
        scope: global
        enabled: false
        masked: true
