---
- name: "[ HELIX EDITOR ]"
  hosts: all

  tasks:

    - name: Ensure helix is installed
      become: true
      community.general.pacman:
        name: helix
        state: present

    - name: Ensure helix config dir exists
      ansible.builtin.file:
        path: "{{ home }}/.config/helix"
        state: directory
        mode: "0755"

    - name: Place helix config
      ansible.builtin.template:
        src: ../templates/helix-config.toml.j2
        dest: "{{ home }}/.config/helix/config.toml"
        mode: "0600"
