---
- name: "[ HYPRLAND ]"
  hosts: all

  vars:
    _hypr_config_dir_default: "{{ home }}/.config/hypr"
    _hypr_config_dir: "{{ hypr_config_dir | default(_hypr_config_dir_default)}}"
    _hypr_kb_layout: "{{ hypr_kb_layout | default('de') }}"
    _hypr_kb_variant: "{{ hypr_kb_variant | default('deadacute') }}"
    _wallpaper_default_path: "{{ home }}/.wallpapers"
    _wallpaper_path: "{{ wallpaper_path | default(_wallpaper_default_path) }}"
    _tofi_font: "{{ tofi_font | default('/usr/share/fonts/TTF/FiraSans-Regular.ttf') }}"

  tasks:

    - name: Ensure required packages are installed
      become: true
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - hyprland
        - qt6-wayland
        - qt5-wayland
        - xdg-desktop-portal-hyprland
        - xdg-desktop-portal-gtk
        - dunst
        - manjaro-pipewire
        - waybar
        - hyprpaper
        - waypaper
        - tofi
        - btop
        - helvum
        - bluetui
        - pacman-contrib
        - qt5ct
        - qt6ct

    - name: Kvantum theming
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - kvantum
        - kvantum-manjaro
        - kvantum-qt5
        - kvantum-theme-matcha
        - kvantum-theme-materia

    - name: Ensure xdg desktop portal dir exists
      ansible.builtin.file:
        dest: "{{ home }}/.config/xdg-desktop-portal"
        state: directory
        mode: "0755"

    - name: Ensure hyprland config dir exists
      ansible.builtin.file:
        path: "{{ _hypr_config_dir }}"
        state: directory
        mode: "0750"
      tags: ["config", "hyprland"]

    - name: Configure hyprland
      ansible.builtin.template:
        src: ../templates/hyprland.conf.j2
        dest: "{{ _hypr_config_dir }}/hyprland.conf"
        mode: "0644"
      tags: ["config", "hyprland"]

    - name: Stats for hyprpaper config
      ansible.builtin.stat:
        path: "{{ _hypr_config_dir }}/hyprpaper.conf"
      register: _hyprpaper_conf
      tags: ["config", "hyprland"]

    - name: Touch hyprpaper config
      when: not _hyprpaper_conf.stat.exists
      ansible.builtin.file:
        path: "{{ _hypr_config_dir }}/hyprpaper.conf"
        state: touch
        mode: "0644"
      tags: ["config", "hyprland"]

    - name: Configure hyprpaper
      ansible.builtin.copy:
        dest: "{{ _hypr_config_dir }}/hyprpaper.conf"
        mode: "0644"
        content: |
          splash = false
          icp = on
      tags: ["config", "hyprland"]

    - name: Configure KDE file chooser
      ansible.builtin.copy:
        content: |-
          [preferred]
          default=hyprland;gtk
          org.freedesktop.impl.portal.FileChooser=kde
        dest: "{{ home }}/.config/xdg-desktop-portal/hyprland-portals.conf"
        mode: "0644"
      tags: ["config"]

    - name: Make sure plasma polkit agent is started
      ansible.builtin.systemd_service:
        name: plasma-polkit-agent.service
        state: started
        scope: user

    - name: Ensure waybar config paths exists
      tags: ["config", "waybar"]
      ansible.builtin.file:
        path: "{{ home }}/.config/waybar/scripts"
        state: directory
        mode: "0750"

    - name: Configure waybar
      tags: ["config", "waybar"]
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ home }}/.config/waybar/{{ item.dest }}"
        mode: "0644"
      loop:
        - src: ../templates/waybar.config.j2
          dest: config.jsonc
        - src: ../templates/waybar.style.j2
          dest: style.css

    - name: Copy bash utils to local bin
      tags: ["config", "waybar"]
      ansible.builtin.copy:
        src: "../scripts/{{ item }}"
        dest: "{{ home }}/.config/waybar/scripts"
        mode: "0750"
      loop:
        - change-volume.sh
        - check-arch-updates.sh
        - check-aur-updates.sh
