---
- hosts: all
  tasks:
    - name: Install i3-gaps and some optional
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - i3-gaps
        - dmenu
        - i3lock
        - i3status
        - lxappearance
        - arandr
