---
- name: "[ LeftWM ]"
  hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    config_dir: "{{ home }}/.config/leftwm"
    config_path: "{{ config_dir }}/config.ron"
    global_up_path: "{{ config_dir }}/up"

  tasks:

    - name: Install leftwm
      become: true
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - leftwm
        - i3lock
        - polybar
        - rofi
        - nitrogen
        - feh
        - dunst
        - pcmanfm
        - network-manager-applet
        - pulsemixer
        - pulseaudio-ctl
        - pavucontrol
        - lxappearance
        - pkgconf
        - qt5ct-kde

    - name: Ensure leftwm theme dir is present
      ansible.builtin.file:
        path: "{{ config_dir }}/themes"
        state: directory
        mode: 0750

    - name: Link theme
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/themes/minimal-leftwm-theme"
        dest: "{{ config_dir }}/themes/current"
        state: link

    - name: Check stats of fresh installed configuration
      ansible.builtin.stat:
        path: "{{ config_path }}"
      register: conf_file

    - name: Remove configuration in case of regular file
      ansible.builtin.file:
        path: "{{ config_path }}"
        state: absent
      when: conf_file.stat.isreg is defined and conf_file.stat.isreg

    - name: Link leftwm configuration
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/config.ron"
        dest: "{{ config_path }}"
        state: link

    - name: Link global leftwm up script
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/up"
        dest: "{{ global_up_path }}"
        state: link

    - name: Pretend that LeftWM is KDE to get proper theme
      ansible.builtin.blockinfile:
        create: true
        path: "{{ home }}/.xprofile"
        mode: 0644
        marker: "# {mark} LEFTWM CONF USING ANSIBLE"
        block: |
          if [ "$XDG_CURRENT_DESKTOP" = "LeftWM" ]; then
              export XDG_CURRENT_DESKTOP="KDE"
          fi

    - name: Set QT_QPA_PLATFORMTHEME
      ansible.builtin.lineinfile:
        path: "{{ home }}/.xprofile"
        mode: 0644
        line: export QT_QPA_PLATFORMTHEME="qt5ct"
