---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    config_dir: "{{ home }}/.config/leftwm"
    config_path: "{{ config_dir }}/config.toml"
    leftwm_theme_src: /usr/local/src/leftwm-theme

  handlers:
    - name: build leftwm-theme
      ansible.builtin.command:
        chdir: "{{ leftwm_theme_src }}"
        cmd: cargo build --release

    - name: install leftwm-theme
      become: true
      ansible.builtin.command:
        chdir: "{{ leftwm_theme_src }}"
        cmd: install -s -Dm755 ./target/release/leftwm-theme -t /usr/local/bin

    - name: update leftwm themes
      ansible.builtin.command:
        cmd: leftwm-theme update

  tasks:

    - name: Install leftwm
      become: true
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - leftwm
        - i3lock
        - polybar
        - picom
        - rofi
        - nitrogen
        - dunst
        - pcmanfm
        - network-manager-applet
        - blueberry
        - volumeicon
        - pulsemixer
        - pavucontrol
        - lxappearance

    - name: Ensure leftwm theme dir is present
      ansible.builtin.file:
        path: "{{ config_dir }}/themes"
        state: directory
        mode: 0750

    - name: Link theme
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/themes/minimal-leftwm-theme"
        dest: "{{ config_dir }}/themes/current"
        state: link

    - name: Check stats of fresh installed configuration
      ansible.builtin.stat:
        path: "{{ config_path }}"
      register: conf_file

    - name: Remove configuration in case of regular file
      ansible.builtin.file:
        path: "{{ config_path }}"
        state: absent
      when: conf_file.stat.isreg is defined and conf_file.stat.isreg

    - name: Link leftwm configuration
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/config.toml"
        dest: "{{ config_path }}"
        state: link

    - name: Ensure leftwm-theme dir is present
      become: true
      ansible.builtin.file:
        path: "{{ leftwm_theme_src }}"
        state: directory
        mode: 0755
        owner: "{{ lookup('env', 'USER') }}"

    - name: Get leftwm-theme
      ansible.builtin.git:
        repo: https://github.com/leftwm/leftwm-theme
        dest: /usr/local/src/leftwm-theme
        version: master
      notify:
        - build leftwm-theme
        - install leftwm-theme
        - update leftwm themes
