---
- name: "[ LeftWM ]"
  hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    config_dir: "{{ home }}/.config/leftwm"
    config_path: "{{ config_dir }}/config.ron"
    global_up_path: "{{ config_dir }}/up"
    __leftwm_src_path: "{{ leftwm_src_path | default(lookup('env', 'HOME')) }}/.leftwm"
    __leftwm_version: "{{ leftwm_version | default('eca88e5ab4aef8a2ed52e25d8c9a4c2345b1afdb') }}"

  handlers:

    - name: Build leftwm
      ansible.builtin.command:
        chdir: "{{ __leftwm_src_path }}"
        cmd: cargo build --profile optimized

    - name: Clear leftwm build dir
      ansible.builtin.command:
        chdir: "{{ __leftwm_src_path }}"
        cmd: cargo clean

    - name: Install leftwm executables to /usr/bin
      become: true
      ansible.builtin.command:
        chdir: "{{ __leftwm_src_path }}"
        cmd: "install -s -Dm755 target/optimized/{{ item }} -t /usr/bin"
      loop:
        - leftwm
        - leftwm-worker
        - lefthk-worker
        - leftwm-state
        - leftwm-check
        - leftwm-command

    - name: Copy leftwm.desktop to xsessions
      become: true
      ansible.builtin.copy:
        src: "{{ __leftwm_src_path }}/leftwm.desktop"
        dest: /usr/share/xsessions/
        mode: 0644

  tasks:

    - name: Check if cargo is installed
      ansible.builtin.command:
        cmd: zsh -c 'command -v cargo'
      changed_when: false
      failed_when: false
      register: cargo_cmd

    - name: Cancel further execution if cargo is not available
      ansible.builtin.assert:
        that:
          - cargo_cmd.stdout | length > 0
        fail_msg: "Please install rust and cargo. Take a look at the rust playbook"

    - name: Ensure leftwm is not installed via package manager
      become: true
      yay:
        name: leftwm
        state: absent

    - name: Ensure leftwm src path exists
      ansible.builtin.file:
        path: "{{ __leftwm_src_path }}"
        state: directory
        mode: 0755

    - name: Get leftwm sources
      ansible.builtin.git:
        repo: https://github.com/leftwm/leftwm.git
        dest: "{{ __leftwm_src_path }}"
        version: "{{ __leftwm_version }}"
      notify:
        - Build leftwm
        - Install leftwm executables to /usr/bin
        - Copy leftwm.desktop to xsessions
        - Clear leftwm build dir

    - name: Install leftwm utils
      become: true
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - i3lock
        - polybar
        - rofi
        - nitrogen
        - feh
        - dunst
        - pcmanfm
        - network-manager-applet
        - pulsemixer
        - pulseaudio-ctl
        - pavucontrol
        - lxappearance
        - pkgconf
        - qt5ct-kde

    - name: Ensure leftwm theme dir is present
      ansible.builtin.file:
        path: "{{ config_dir }}/themes"
        state: directory
        mode: 0750

    - name: Link theme
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/themes/minimal-leftwm-theme"
        dest: "{{ config_dir }}/themes/current"
        state: link

    - name: Check stats of fresh installed configuration
      ansible.builtin.stat:
        path: "{{ config_path }}"
      register: conf_file

    - name: Remove configuration in case of regular file
      ansible.builtin.file:
        path: "{{ config_path }}"
        state: absent
      when: conf_file.stat.isreg is defined and conf_file.stat.isreg

    - name: Link leftwm configuration
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/config.ron"
        dest: "{{ config_path }}"
        state: link

    - name: Link global leftwm up script
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/up"
        dest: "{{ global_up_path }}"
        state: link

    - name: Pretend that LeftWM is KDE to get proper theme
      ansible.builtin.blockinfile:
        create: true
        path: "{{ home }}/.xprofile"
        mode: 0644
        marker: "# {mark} LEFTWM CONF USING ANSIBLE"
        block: |
          if [ "$XDG_CURRENT_DESKTOP" = "LeftWM" ]; then
              export XDG_CURRENT_DESKTOP="KDE"
          fi

    - name: Set QT_QPA_PLATFORMTHEME
      ansible.builtin.lineinfile:
        path: "{{ home }}/.xprofile"
        mode: 0644
        line: export QT_QPA_PLATFORMTHEME="qt5ct"
