---
- hosts: all
  gather_facts: false

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    config_dir: "{{ home }}/.config/leftwm"
    config_path: "{{ config_dir }}/config.toml"

  tasks:

    - name: Install leftwm
      become: true
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - leftwm
        - polybar
        - picom
        - rofi
        - nitrogen
        - dunst
        - slock

    - name: Ensure leftwm theme dir is present
      ansible.builtin.file:
        path: "{{ config_dir }}/themes"
        state: directory
        mode: 0750

    - name: Link theme
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/sommerbrise"
        dest: "{{ config_dir }}/themes/current"
        state: link

    - name: Check stats of fresh installed configuration
      ansible.builtin.stat:
        path: "{{ config_path }}"
      register: conf_file

    - name: Remove configuration in case of regular file
      ansible.builtin.file:
        path: "{{ config_path }}"
        state: absent
      when: conf_file.stat.isreg is defined and conf_file.stat.isreg

    - name: Link leftwm configuration
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/leftwm/config.toml"
        dest: "{{ config_path }}"
        state: link
