---
- name: Magic wormhole is required to savely sent files
  hosts: all

  tasks:
    - name: Ensure magic wormhole is installed
      become: true
      yay:
        name: wormhole-rs
        state: present
