---
- name: "[ MINICONDA ]"
  hosts: all

  vars:
    default_miniconda_home: "{{ home }}/miniconda"
    miniconda_url: "https://repo.anaconda.com/miniconda/Miniconda3-py310_22.11.1-1-Linux-x86_64.sh"
    miniconda_checksum: "sha256:00938c3534750a0e4069499baf8f4e6dc1c2e471c86a59caa0dd03f4a9269db6"
    miniconda_dir: "{{ miniconda_home | default(default_miniconda_home) }}"

  handlers:
    - name: Remove miniconda setup script
      ansible.builtin.file:
        path: /tmp/miniconda.sh
        state: absent

    - name: Update conda
      ansible.builtin.command:
        cmd: "{{ miniconda_dir }}/bin/conda update conda --yes -q"

  tasks:
    - name: Check if miniconda exists
      ansible.builtin.stat:
        path: "{{ miniconda_home }}/bin/conda"
      register: conda_bin

    - name: Download miniconda
      ansible.builtin.get_url:
        url: "{{ miniconda_url }}"
        dest: "/tmp/miniconda.sh"
        mode: 0750
        checksum: "{{ miniconda_checksum }}"
      when: not conda_bin.stat.exists
      register: miniconda_download

    - name: Run miniconda silent installation routine
      ansible.builtin.command:
        cmd: "bash /tmp/miniconda.sh -b -p {{ miniconda_dir }}"
        creates: "{{ miniconda_dir }}"
      when: miniconda_download.state is defined and miniconda_download.state == 'file'
      notify:
        - Remove miniconda setup script
        - Update conda

    - name: Add miniconda to the path
      ansible.builtin.lineinfile:
        path: "{{ path_file_path }}"
        line: "export PATH={{ miniconda_dir }}/bin:$PATH"
