---
- hosts: all

  vars:
    minikube_driver: "{{ local_minikube_driver | default('kvm2') }}"

  handlers:
    - name: Configure minikube driver
      ansible.builtin.command: minikube config set driver "{{ minikube_driver }}"

  tasks:
    - name: Install minikube and its dependencies
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - minikube
        - kubectl
        - qemu-desktop
        - virt-manager
        - libvirt
      notify:
        - Configure minikube driver

    - name: Ensure the current user is part of the libvirt group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        groups:
          - libvirt
        append: true

    - name: Ensure the libvirtd service is started
      become: true
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: true
