---
- name: "[ NEOVIM ]"
  hosts: all

  vars:
    aliases_path: "{{ home }}/.aliases"
    neovim_config_path: "{{ home }}/.config/nvim"

  tasks:
    - name: Install neovim and required packages
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: ["neovim", "xclip", "luarocks"]

    - name: Check if neovim dir is already present
      ansible.builtin.stat:
        path: "{{ neovim_config_path }}"
      register: neovim_config

    - name: Remove neovim config dir if it is a standard directory
      ansible.builtin.file:
        path: "{{ home }}/.config/nvim"
        state: absent
        mode: "0755"
      when: neovim_config.stat.exists and not neovim_config.stat.islnk

    - name: Link configuration files
      ansible.builtin.file:
        state: link
        src: "{{ home }}/dotfiles/neovim"
        path: "{{ home }}/.config/nvim"

    - name: Set the alias for vim to nvim
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias vim='nvim'"
