---
- name: "[ NEOVIM ]"
  hosts: all

  vars:
    aliases_path: "{{ home }}/.aliases"
    neovim_config_path: "{{ home }}/.config/nvim"
    _terminal_emulator: "{{ terminal_emulator | default('ghostty') }}"

  tasks:
    - name: Install neovim and required packages
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: ["neovim", "xclip", "luarocks"]

    - name: Check if neovim dir is already present
      ansible.builtin.stat:
        path: "{{ neovim_config_path }}"
      register: neovim_config

    - name: Remove neovim config dir if it is a standard directory
      ansible.builtin.file:
        path: "{{ home }}/.config/nvim"
        state: absent
        mode: "0755"
      when: neovim_config.stat.exists and not neovim_config.stat.islnk

    - name: Link configuration files
      ansible.builtin.file:
        state: link
        src: "{{ home }}/dotfiles/neovim"
        path: "{{ home }}/.config/nvim"

    - name: Set the alias for vim to nvim
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias vim='nvim'"

    - name: Build custom neovim-ui.desktop non terminal version
      ansible.builtin.copy:
        dest: "{{ home }}/.local/share/applications/nvim-ui.desktop"
        mode: "0644"
        content: |
          [Desktop Entry]
          Name=Neovim UI
          GenericName=Text Editor
          Comment=Edit text files
          TryExec=nvim
          Exec={{ _terminal_emulator }} -e nvim %F
          Terminal=false
          Type=Application
          Keywords=Text;editor;
          Icon=nvim
          Categories=Utility;TextEditor;
          StartupNotify=false
          MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;

    - name: Ensure custom mimeapps.list exists
      ansible.builtin.file:
        path: "{{ home }}/.local/share/applications/mimeapps.list"
        state: touch
        mode: "0644"

    - name: Set nvim-ui as default on xdg-mime - text/plain
      ansible.builtin.blockinfile:
        path: "{{ home }}/.local/share/applications/mimeapps.list"
        block: |
          [Default Applications]
          text/plain=nvim-ui.desktop
