---
- name: "[ NEOVIM ]"
  hosts: all

  vars:
    aliases_path: "{{ lookup('env', 'HOME') }}/.aliases"

  tasks:
    - name: Install neovim and required packages
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: ["neovim", "xclip", "luarocks"]

    - name: Ensure neovim config directory exists
      ansible.builtin.file:
        path: "{{ home }}/.config/nvim"
        state: absent
        mode: "0755"

    - name: Link configuration files
      ansible.builtin.file:
        state: link
        src: "{{ home }}/dotfiles/neovim"
        path: "{{ home }}/.config/nvim"

    - name: Set the alias for vim to nvim
      ansible.builtin.lineinfile:
        path: "{{ aliases_path }}"
        line: "alias vim='nvim'"
