---
- name: "[ NOCTALIA ]"
  hosts: all

  vars:
    _noctalia_config_path: "{{ home }}/.config/noctalia"
    _noctalia_install_optional: "{{ noctalia_config_path | default(true) }}"

  tasks:

    - name: Ensure noctalia is installed
      become: true
      community.general.pacman:
        name: "noctalia"
        state: present

    - name: Install optional packages
      become: true
      when: _noctalia_install_optional
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - ddcutil
        - power-profiles-daemon
        - upower
        - wlsunset

    - name: Ensure noctalia shell config dir is present
      ansible.builtin.file:
        path: "{{ _noctalia_config_path }}"
        state: directory
        mode: "0755"
