---
- name: Install and configure ollama
  hosts: all

  vars:
    _ollama_default_bin: "{{ home }}/.local/bin/ollama"
    _ollama_bin: "{{ ollama_bin | default(_ollama_default_bin) }}"
    _ollama_version: "{{ ollama_version | default('v0.1.31') }}"
    _ollama_github_download_url: "https://github.com/ollama/ollama/releases/download/{{ _ollama_version }}/ollama-linux-amd64"
    _ollama_download_url: "{{ ollama_download_url | default(_ollama_github_download_url) }}"
    _ollama_bin_checksum: "sha256:9d9a24ed741bf9d88c8e9df6865371681316aee298433d0291e86295045bfa96"
    _ollama_default_model_store: "{{ home }}/.ollama/models"
    _ollama_model_store: "{{ ollama_model_store | default(_ollama_default_model_store) }}"

  tasks:

    - name: Download ollama binary
      ansible.builtin.get_url:
        url: "{{ _ollama_download_url }}"
        dest: "{{ _ollama_bin }}"
        mode: "0750"
        checksum: "{{ _ollama_bin_checksum }}"

    - name: Configure ollama systemd service
      ansible.builtin.template:
        src: ../templates/ollama_systemd_service.j2
        dest: "{{ home }}/.config/systemd/user/ollama.service"
        mode: "0640"

    - name: Ensure model store exists
      ansible.builtin.file:
        path: "{{ _ollama_model_store }}"
        state: directory
        mode: "0750"

    - name: Create ollama systemd service
      ansible.builtin.systemd:
        name: ollama
        state: stopped
        enabled: false
        scope: user
        daemon_reload: true
