---
- name: "[ PIPEWIRE ]"
  hosts: all

  tasks:
    - name: Manage packages
      become: true
      community.general.pacman:
        - name: "{{ item.name }}"
          state: "{{ item.state | default(present) }}"
      loop:
        - name: pulseaudio-ctl
          state: absent
        - name: pulseaudio-bluetooth
          state: absent
        - name: manjaro-pipewire
        - name: easyeffects
        - name: pipewire-jack
