---
- name: "[ PYTHON ]"
  hosts: all
  gather_facts: false

  handlers:
    - name: Install python packaging utils
      become: true
      ansible.builtin.command:
        cmd: "pipx install --force {{ item }}"
      loop:
        - poetry
        - pdm
      changed_when: true

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    __ipython_highlighting_style: "{{ ipython_highlighting_style | default('nord') }}"
    __ipython_true_color: "{{ ipython_true_color | default(True) }}"

  tasks:

    - name: Ensure python and python development packages are installed
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - python
        - ipython
        - ruff
        - ruff-lsp
        - python-debugpy
        - python-pytest
        - python-isort
        - python-black
        - python-cookiecutter
        - python-passlib
        - jupyterlab
        - python-pipx
        - python-jmespath

    - name: Add ~/.local/bin to ~/.path
      ansible.builtin.lineinfile:
        path: "{{ path_file_path }}"
        line: "export PATH={{ home }}/.local/bin:$PATH"

    - name: Check if an ipython profile exists
      ansible.builtin.stat:
        path: "{{ home }}/.ipython/profile_default"
      register: ipython_default_profile

    - name: Create ipython profile
      ansible.builtin.command:
        cmd: ipython profile create
      when: not ipython_default_profile.stat.exists
      changed_when: not ipython_default_profile.stat.exists

    - name: Configure ipython
      ansible.builtin.template:
        src: ../templates/ipython_config.py.j2
        dest: "{{ home }}/.ipython/profile_default/ipython_config.py"
        mode: "0640"
