---
- hosts: all
  gather_facts: false

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    poetry_script: "{{ home }}/.local/bin/poetry"
    poetry_venv: "{{ home }}/.local/share/pypoetry"

  tasks:
    - name: Ensure python and python development packages are installed
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - python
        - pyright
        - python-debugpy
        - python-pyflakes
        - python-pytest
        - python-isort
        - python-black
        - python-cookiecutter

    - name: Remove current poetry script
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ poetry_script }}"
        - "{{ poetry_venv }}"
      when: poetry_update | bool

    - name: Check if poetry is already installed
      ansible.builtin.stat:
        path: "{{ poetry_script }}"
      register: poetry_bin

    - name: Install poetry
      block:
        - name: Create temporary file
          ansible.builtin.tempfile:
            state: file
            prefix: poetry
            suffix: .py
          register: tempfile

        - name: Download poetry installation script
          ansible.builtin.get_url:
            url: https://install.python-poetry.org
            dest: "{{ tempfile.path }}"
            checksum: sha256:761cdefb65de97882482d5edf29de6d90e42917447aabfde63a693206c4550c6
            mode: 0640

        - name: Run the installation script
          ansible.builtin.shell: "cat {{ tempfile.path }} | /usr/bin/python3 -"
          args:
            warn: false
          changed_when: true

      when: not poetry_bin.stat.exists

    - name: Add ~/.local/bin to ~/.path
      ansible.builtin.lineinfile:
        path: "{{ path_file_path }}"
        line: "export PATH={{ home }}/.local/bin:$PATH"
