---
- name: "[ PYTHON ]"
  hosts: all
  gather_facts: false

  handlers:
    - name: Install python packaging utils
      ansible.builtin.command:
        cmd: "pipx install --force {{ item }}"
      loop:
        - pdm
        - poetry
      changed_when: true

    - name: Install pdm completions
      ansible.builtin.shell:
        # use full path, pdm may not be present inside $PATH yet
        cmd: "{{ home }}/.local/bin/pdm completion zsh > {{ zsh_custom }}/plugins/pdm/_pdm"
      changed_when: true

  vars:
    default_zsh_custom: "{{ home }}/.oh-my-zsh/custom"
    zsh_custom: "{{ lookup('env', 'ZSH_CUSTOM') | default(default_zsh_custom, true) }}"
    __ipython_highlighting_style: "{{ ipython_highlighting_style | default('nord') }}"
    __ipython_true_color: "{{ ipython_true_color | default(True) }}"

  tasks:

    - name: Ensure python and python development packages are installed
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - python
        - ipython
        - tk
        - python-mccabe
        - python-debugpy
        - python-pytest
        - python-pyflakes
        - python-rope
        - python-isort
        - python-black
        - python-cookiecutter
        - python-passlib
        - jupyterlab
        - python-pipx
        - python-jmespath
        - yapf
        - python-whatthepatch

    - name: Check pylsp command
      ansible.builtin.stat:
        path: "{{ home }}/.local/bin/pylsp"
      register: __pylsp

    - name: Install pylsp using pipx
      when: not __pylsp.stat.exists
      changed_when: true
      ansible.builtin.command:
        cmd: "pipx install --force 'python-lsp-server[all]'"

    - name: Add ~/.local/bin to ~/.path
      ansible.builtin.lineinfile:
        path: "{{ path_file_path }}"
        line: "export PATH={{ home }}/.local/bin:$PATH"

    - name: Check if an ipython profile exists
      ansible.builtin.stat:
        path: "{{ home }}/.ipython/profile_default"
      register: ipython_default_profile

    - name: Create ipython profile
      ansible.builtin.command:
        cmd: ipython profile create
      when: not ipython_default_profile.stat.exists
      changed_when: not ipython_default_profile.stat.exists

    - name: Configure ipython
      ansible.builtin.template:
        src: ../templates/ipython_config.py.j2
        dest: "{{ home }}/.ipython/profile_default/ipython_config.py"
        mode: "0640"

    - name: Ensure pdm dir exists in oh-my-zsh plugins
      ansible.builtin.file:
        path: "{{ home }}/.oh-my-zsh/custom/plugins/pdm"
        mode: "0750"
        state: directory
      notify:
        - Install python packaging utils
        - Install pdm completions
