---
- hosts: all
  gather_facts: false

  handlers:
    - name: generate qtile type stubs
      ansible.builtin.command: >
        stubgen
        -o {{ pytypestubs }}
        {{ venv }}/lib/python3.10/site-packages/libqtile

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    venv: "{{ lookup('env', 'VIRTUAL_ENV') }}"
    pytypestubs: "{{ home }}/dotfiles/.pytypestubs"
    config_dir: "{{ home }}/.config/qtile"

  tasks:
    - name: Collect stat for python stubs
      ansible.builtin.stat:
        path: "{{ pytypestubs }}"
      register: stubs_dir

    - name: Create python type stubs directory
      ansible.builtin.file:
        path: "{{ pytypestubs }}"
        mode: 0750
        state: directory
      notify: generate qtile type stubs

    - name: Ensure qtile is installed
      become: true
      community.general.pacman:
        name: qtile
        state: present
      notify: generate qtile type stubs

    - name: Ensure additional components are installed
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - picom
        - dmenu

    - name: Make configuration directory
      ansible.builtin.file:
        path: "{{ config_dir }}"
        state: directory
        mode: 0755

    - name: Link qtile config
      ansible.builtin.file:
        path: "{{ config_dir }}/config.py"
        src: "{{ home }}/dotfiles/qtile/config.py"
        state: link
