- name: "[ QTILE ]"
  hosts: all

  tasks:
    - name: Ensure required packages are installed
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - qtile
        - psutil
