---
- hosts: all
  gather_facts: false

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    rofi_dotfiles: "{{ home }}/dotfiles/rofi"
    config_dir: "{{ home }}/.config/rofi"

  tasks:

    - name: Install rofi
      become: true
      yay:
        name: "{{ item }}"
        state: present
      loop:
        - rofi

    - name: Link rofi to ~/.config
      ansible.builtin.file:
        src: "{{ rofi_dotfiles }}"
        dest: "{{ config_dir }}"
        state: link
