---
- name: "[ TOFI ]"
  hosts: all

  tasks:
    - name: Ensure tofi is installed
      become: true
      community.general.pacman:
        name: tofi
        state: present

    - name: Ensure tofi config path exists
      tags: ["config"]
      ansible.builtin.file:
        path: "{{ home }}/.config/tofi"
        state: directory
        mode: "0750"

    - name: Configure tofi
      tags: ["config"]
      ansible.builtin.copy:
        dest: "{{ home }}/.config/tofi/config"
        mode: "0644"
        content: |
          width = 100%
          height = 100%
          border-width = 0
          outline-width = 0
          padding-left = 35%
          padding-top = 35%
          result-spacing = 25
          num-results = 5
          font = Vollkorn
          background-color = #000C
          text-color = #e5e9f0
          selection-color = #d08770
