- name: "[ UDISKIE ]"
  hosts: all

  tasks:

    - name: Ensure udiskie is installed
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - udiskie
        - libappindicator-gtk3


    - name: Ensure udiskie config dir is present
      ansible.builtin.file:
        path: "{{ home }}/.config/udiskie"
        state: directory
        mode: "0750"

    - name: Configure udiskie
      ansible.builtin.copy:
        dest: "{{ home }}/.config/udiskie/config.yml"
        mode: "0644"
        content: |
          program_options:
            tray: true
            file_manager: xdg-open
            automount: false
            terminal: ghostty --working-directory
