---
- name: "[ VERACRYPT ]"
  hosts: all

  vars:
    systemd_user_dir: "{{ home }}/.config/systemd/user"
    umount_veracrypt_script: "{{ home }}/.local/bin/umount_veracrypt_volumes"
    umount_veracrypt_service: "{{ systemd_user_dir }}/umount_veracrypt_volumes.service"

  tasks:

    - name: Install veracrypt
      become: true
      community.general.pacman:
        name: veracrypt
        state: present

    - name: Place unmount all shell script
      ansible.builtin.template:
        src: ../templates/umount_veracrypt_volumes.sh.j2
        dest: "{{ umount_veracrypt_script }}"
        mode: "0750"

    - name: Add umount veracrypt devices as systemd user service
      ansible.builtin.template:
        src: ../templates/umount_veracrypt_unit.service.j2
        dest: "{{ umount_veracrypt_service }}"
        mode: "0644"

    - name: Make 'veracrypt' command available to user without asking for password
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ ansible_env.USER }}"
        create: true
        mode: "0600"
        owner: root
        line: "{{ ansible_env.USER }} ALL=NOPASSWD: /usr/bin/veracrypt"

    - name: Enable unmount systemd user unit
      ansible.builtin.systemd:
        name: umount_veracrypt_volumes.service
        state: stopped
        daemon_reload: true
        enabled: true
        scope: user
