---
- name: "[ VIM ]"
  hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"

  handlers:
    - name: Run ycm installation
      ansible.builtin.command:
        cmd: '/usr/bin/python3 install.py'
        chdir: "{{ ansible_env.HOME }}/.vim/bundle/YouCompleteMe"
      changed_when: true

    - name: Install vim plugins
      ansible.builtin.command:
        cmd: "vim -u {{ home }}/.vimrc.bundles +PluginInstall +qall"
      changed_when: true

  tasks:
    - name: Install vim and required packages
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: ["cmake", "make", "gcc", "vim"]

    - name: Check for vimrc link
      ansible.builtin.stat:
        path: "{{ home }}/.vimrc"
      register: vimrc_link

    - name: Link configuration files
      ansible.builtin.file:
        state: link
        src: "{{ item.src }}"
        path: "{{ item.path }}"
      loop:
        - src: "{{ home }}/dotfiles/vimrc"
          path: "{{ home }}/.vimrc"
        - src: "{{ home }}/dotfiles/vim/bundle.vim"
          path: "{{ home }}/.vimrc.bundles"
        - src: "{{ home }}/dotfiles/vim/map.vim"
          path: "{{ home }}/.vimrc.map"
      notify: install vim plugins
      register: vim_links

    - name: Check stats for YouCompleteMe
      ansible.builtin.stat:
        path: "{{ home }}/.vim/bundle/YouCompleteMe"
      register: ycm_stat

    - name: Get YouCompleteMe
      ansible.builtin.git:
        repo: https://github.com/ycm-core/YouCompleteMe.git
        dest: "{{ home }}/.vim/bundle/YouCompleteMe"
        version: master
      when: ycm_stat.stat.isdir is not defined or not ycm_stat.stat.isdir
      notify: run ycm installation

    - name: Update vim plugins
      ansible.builtin.command:
        cmd: "vim -u {{ home }}/.vimrc.bundles +PluginUpdate +qall"
      when: vimrc_link.stat.islnk is defined and vimrc_link.stat.islnk
      changed_when: vimrc_link.stat.islnk is defined and vimrc_link.stat.islnk
      notify: run ycm installation
