---
- name: Install and configure virtualization support
  hosts: all
  gather_facts: true

  handlers:

    - name: Install vagrant-dns plugin
      ansible.builtin.command:
        cmd: vagrant plugin install vagrant-dns
      changed_when: true
      environment: "{{ __vagrant_env }}"

  vars:
    __vagrant_env:
      VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT: "1"

  tasks:
    - name: Install qemu/kvm, libvirt and its dependencies
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - qemu-desktop
        - virt-manager
        - libvirt
        - iptables-nft
        - dnsmasq
        - dmidecode
        - bridge-utils
        - guestfs-tools
        - swtpm

    - name: Ensure the current user is part of the libvirt group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        groups:
          - libvirt
        append: true

    - name: Ensure the libvirtd service is started
      become: true
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: true

    - name: Set the UNIX domain socket group ownership
      become: true
      ansible.builtin.lineinfile:
        path: /etc/libvirt/libvirtd.conf
        regexp: '^unix_sock_group '
        insertafter: '^#unix_sock_group '
        line: 'unix_sock_group = "libvirt"'

    - name: Set the UNIX socket permissions for the R/W socket.
      become: true
      ansible.builtin.lineinfile:
        path: /etc/libvirt/libvirtd.conf
        regexp: '^unix_sock_rw_perms '
        insertafter: '^#unix_sock_rw_perms '
        line: 'unix_sock_rw_perms = "0770"'

    - name: Configure libvirt default uri
      ansible.builtin.lineinfile:
        path: "{{ home }}/.xprofile"
        line: "export LIBVIRT_DEFAULT_URI='qemu:///system'"

    - name: Install vagrant if necessary
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - vagrant

    - name: List vagrant plugins
      ansible.builtin.command:
        cmd: vagrant plugin list
      environment: "{{ __vagrant_env }}"
      changed_when: false
      register: vagrant_plugins

    - name: Check vagrant plugin vagrant-dns
      ansible.builtin.command:
        cmd: vagrant plugin list
      changed_when: '"vagrant-dns" not in vagrant_plugins.stdout'
      notify: Install vagrant-dns plugin

    - name: Make libvirt the default provider for vagrant
      ansible.builtin.lineinfile:
        path: "{{ home }}/.zprofile"
        line: 'export VAGRANT_DEFAULT_PROVIDER=docker'
