---
- name: "[ VISUAL STUDIO CODE ]"
  hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    vscode_conf_dir: "{{ home }}/.config/Code/User"
    vscode_user_settings_file: "{{ vscode_conf_dir }}/settings.json"
    extensions:
      present:
        - arcticicestudio.nord-visual-studio-code
        - coolbear.systemd-unit-file
        - DotJoshJohnson.xml
        - eamodio.gitlens
        - gerane.Theme-Zenburn
        - jebbs.plantuml
        - jmreicha.tender
        - mechatroner.rainbow-csv
        - mkhl.direnv
        - ms-azuretools.vscode-docker
        - MS-CEINTL.vscode-language-pack-de
        - ms-python.isort
        - ms-python.pylint
        - ms-python.python
        - ms-python.vscode-pylance
        - ms-toolsai.jupyter
        - ms-toolsai.jupyter-keymap
        - ms-toolsai.jupyter-renderers
        - ms-toolsai.vscode-jupyter-cell-tags
        - ms-toolsai.vscode-jupyter-slideshow
        - ms-vscode.cpptools
        - ms-vscode-remote.remote-containers
        - naumovs.color-highlight
        - njpwerner.autodocstring
        - psioniq.psi-header
        - redhat.ansible
        - redhat.java
        - redhat.vscode-yaml
        - rust-lang.rust-analyzer
        - shuworks.vscode-table-formatter
        - stkb.rewrap
        - tamasfe.even-better-toml
        - VisualStudioExptTeam.intellicode-api-usage-examples
        - VisualStudioExptTeam.vscodeintellicode
        - vscjava.vscode-java-debug
        - vscjava.vscode-java-dependency
        - vscjava.vscode-java-pack
        - vscjava.vscode-java-test
        - vscjava.vscode-maven
        - vscode-icons-team.vscode-icons
        - webfreak.debug
        - yzhang.markdown-all-in-one

      absent:
        - TabNine.tabnine-vscode

  tasks:
    - name: Install visual studio code from aur
      become: true
      yay:
        name: visual-studio-code-bin
        state: present

    - name: Select installed extensions
      ansible.builtin.command:
        cmd: "code --list-extensions | sort"
      register: ext_list_result
      changed_when: ext_list_result.stdout_lines | difference(extensions.present) | length > 0

    - name: Set fact of installed extensions
      ansible.builtin.set_fact:
        current_ext: "{{ ext_list_result.stdout_lines }}"

    - name: Set extensions that should be installed
      ansible.builtin.set_fact:
        install_ext: "{{ extensions.present | difference(current_ext) }}"

    - name: Install extensions
      ansible.builtin.command:
        cmd: "code --install-extension {{ item }}"
      loop: "{{ install_ext }}"
      when: install_ext != []
      changed_when: install_ext != []

    - name: Set extensions that should be removed
      ansible.builtin.set_fact:
        uninstall_ext: "{{ extensions.absent | intersect(current_ext) }}"

    - name: Uninstall extensions
      ansible.builtin.command:
        cmd: "code --uninstall-extension {{ item }}"
      loop: "{{ uninstall_ext }}"
      when: uninstall_ext != []
      changed_when: uninstall_ext != []

    - name: Create vs code user dir
      ansible.builtin.file:
        path: "{{ vscode_conf_dir }}"
        state: directory
        mode: "0750"

    - name: Stat of vs code user settings file
      ansible.builtin.stat:
        path: "{{ vscode_user_settings_file }}"
      register: settings

    - name: Delete user settings if necessary
      ansible.builtin.file:
        path: "{{ vscode_user_settings_file }}"
        state: absent
      when: settings.stat.isreg is defined and settings.stat.isreg

    - name: Link configuration
      ansible.builtin.file:
        path: "{{ vscode_user_settings_file }}"
        src: "{{ home }}/dotfiles/vscode/settings.json"
        state: link
