---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    vscode_conf_dir: "{{ home }}/.config/Code/User"
    vscode_user_settings_file: "{{ vscode_conf_dir }}/settings.json"
    extensions:
      present:
        - arcticicestudio.nord-visual-studio-code
        - coolbear.systemd-unit-file
        - DotJoshJohnson.xml
        - eamodio.gitlens
        - golang.go
        - jebbs.plantuml
        - jmreicha.tender
        - matklad.pale-fire
        - mechatroner.rainbow-csv
        - ms-azuretools.vscode-docker
        - MS-CEINTL.vscode-language-pack-de
        - ms-python.python
        - ms-python.vscode-pylance
        - ms-vscode-remote.remote-containers
        - ms-vscode.cpptools
        - njpwerner.autodocstring
        - psioniq.psi-header
        - redhat.ansible
        - redhat.vscode-yaml
        - shuworks.vscode-table-formatter
        - stkb.rewrap
        - TabNine.tabnine-vscode
        - tamasfe.even-better-toml
        - yzhang.markdown-all-in-one
      absent: []

  tasks:
    - name: Install visual studio code from aur
      become: true
      yay:
        name: visual-studio-code-bin
        state: present

    - name: Select installed extensions
      ansible.builtin.command:
        cmd: "code --list-extensions | sort"
      register: ext_list_result
      changed_when: ext_list_result.stdout_lines != extensions.present

    - name: Set fact of installed extensions
      ansible.builtin.set_fact:
        current_ext: "{{ ext_list_result.stdout_lines | sort }}"

    - name: Set extensions that should be installed
      ansible.builtin.set_fact:
        install_ext: "{{ extensions.present | difference(current_ext) }}"

    - name: Install extensions
      ansible.builtin.command:
        cmd: "code --install-extension {{ item }}"
      loop: "{{ install_ext }}"
      when: install_ext != []

    - name: Set extensions that should be removed
      ansible.builtin.set_fact:
        uninstall_ext: "{{ extensions.absent | intersect(current_ext) }}"

    - name: Uninstall extensions
      ansible.builtin.command:
        cmd: "code --uninstall-extension {{ item }}"
      loop: "{{ uninstall_ext }}"
      when: uninstall_ext != []

    - name: Create vs code user dir
      ansible.builtin.file:
        path: "{{ vscode_conf_dir }}"
        state: directory
        mode: 0750

    - name: Stat of vs code user settings file
      ansible.builtin.stat:
        path: "{{ vscode_user_settings_file }}"
      register: settings

    - name: Delete user settings if necessary
      ansible.builtin.file:
        path: "{{ vscode_user_settings_file }}"
        state: absent
      when: settings.stat.isreg is defined and settings.stat.isreg

    - name: Link configuration
      ansible.builtin.file:
        path: "{{ vscode_user_settings_file }}"
        src: "{{ home }}/dotfiles/vscode/settings.json"
        state: link
