---
- name: "[ UNSPLASH DOWNLOAD SCRIPT ]"
  hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"

    dl_wallpaper_script_name: dl_unsplash_wallpaper.sh
    dl_wallpaper_script_path: "{{ home }}/.local/bin/{{ dl_wallpaper_script_name }}"
    dl_wallpaper_desktop_path: "{{ home }}/.config/autostart/dl-unsplash-wallpaper.desktop"
    dl_destination: "{{ home }}/.local/share/wallpapers"
    delete_duplicate_files_script_name: delete_duplicate_files.py
    delete_wallpaper_script_path: "{{ home }}/.local/bin/{{ delete_duplicate_files_script_name }}"
    delete_wallpaper_desktop_path: "{{ home }}/.config/autostart/delete-duplicate-wallpaper.desktop"

    __unsplash_search_word: "{{ unsplash_search_word | default('wallpaper') }}"

  tasks:

    - name: Copy download unsplash wallpaper to local bin
      ansible.builtin.template:
        src: ../templates/download_unsplash_wallpaper.sh.j2
        dest: "{{ dl_wallpaper_script_path }}"
        mode: 0750

    - name: Add contents to dl-unsplash-wallpaper.desktop file
      ansible.builtin.blockinfile:
        path: "{{ dl_wallpaper_desktop_path }}"
        create: true
        mode: 0640
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          [Desktop Entry]
          Exec={{ dl_wallpaper_script_path }}
          Name=download unsplash wallpaper
          Type=Application

    - name: Copy delete duplicate files script to local bin
      ansible.builtin.template:
        src: "../templates/{{ delete_duplicate_files_script_name }}"
        dest: "{{ delete_wallpaper_script_path }}"
        mode: 0750

    - name: Add contents to delete-duplicate-wallpaper.desktop file
      ansible.builtin.blockinfile:
        path: "{{ delete_wallpaper_desktop_path }}"
        create: true
        mode: 0640
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          [Desktop Entry]
          Exec=python {{ delete_wallpaper_script_path }} {{ dl_destination }}
          Name=delete duplicate downloaded unsplash wallpaper
          Type=Application
