---
- hosts: all

  vars:
    home: "{{ lookup('env', 'HOME') }}"

    dl_wallpaper_script_name: dl_unsplash_wallpaper.sh
    dl_wallpaper_script_path: "{{ home }}/.local/bin/{{ dl_wallpaper_script_name }}"
    dl_wallpaper_desktop_path: "{{ home }}/.config/autostart/dl-unsplash-wallpaper.desktop"

    unsplash_search_word: nature

  tasks:

    - name: Copy download unsplash wallpaper to local bin
      ansible.builtin.template:
        src: ../templates/dl_unsplash_wallpaper.sh.j2
        dest: "{{ dl_wallpaper_script_path }}"
        mode: 0750

    - name: Add contents to dl-unsplash-wallpaper.desktop file
      ansible.builtin.blockinfile:
        path: "{{ dl_wallpaper_desktop_path }}"
        create: true
        mode: 0640
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          [Desktop Entry]
          Exec={{ dl_wallpaper_script_path }}
          Name=download unsplash wallpaper
          Type=Application
