---
- name: "[ WOFI ]"
  hosts: all

  tasks:
    - name: Ensure wofi is installed
      become: true
      community.general.pacman:
        name: wofi
        state: present

    - name: Ensure wofi config path exists
      tags: ["config"]
      ansible.builtin.file:
        path: "{{ home }}/.config/wofi"
        state: directory
        mode: "0750"

    - name: Configure wofi
      tags: ["config"]
      ansible.builtin.copy:
        dest: "{{ home }}/.config/wofi/config"
        mode: "0644"
        content: |
          allow_images=true
          term=ghostty
          insensitive=true
          key_up=Ctrl-k
          key_right=Ctrl-l
          key_down=Ctrl-j
          key_left=Ctrl-h

    - name: Style wofi
      tags: ["config"]
      ansible.builtin.template:
        src: ../templates/wofi.style.css.j2
        dest: "{{ home }}/.config/wofi/style.css"
        mode: "0644"
