- name: Configure the X11 environment
  hosts: all

  tasks:
    - name: Set caps lock to control
      ansible.builtin.blockinfile:
        path: "{{ home }}/.Xmodmap"
        create: true
        mode: 0644
        marker: "! {mark} ANSIBLE MANAGED"
        block: |
          clear lock
          clear control
          keycode 66 = Control_L
