---
- name: "[ YAY ]"
  hosts: all
  tasks:
    - name: Install yay
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - yay
        - pkgconf
        - base-devel
        - make

    - name: Install ansible yay module
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/mnussbaum/ansible-yay/master/yay
        dest: ./library/yay
        mode: 0755
