---
- hosts: all
  tasks:
    - name: Install yay
      become: true
      community.general.pacman:
        name: yay
        state: present

    - name: Install ansible yay module
      ansible.builtin.git:
        repo: git@github.com:mnussbaum/ansible-yay.git
        dest: ./library
        version: master
