---
- name: "[ YAY ]"
  hosts: all
  tasks:
    - name: Install yay
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - yay
        - pkgconf
        - base-devel
        - make

    - name: Install ansible yay module
      ansible.builtin.git:
        repo: git@github.com:mnussbaum/ansible-yay.git
        dest: ./library
        version: master
