---
- name: "[ ZOOM ]"
  hosts: all

  vars:
    _zoom_state: "{{ zoom_state | default('present') }}"
    _zoom_pkg_name: zoom
    _zoom_pkg_version: "{{ zoom_pkg_version | default('7.1.5') }}"
    _zoom_pkg_subversion: "{{ zoom_pkg_subversion | default('4332') }}"
    _zoom_checksum: "{{ zoom_checksum | default('d5ca18a754565c569825606646488f9b51b757685fb5788b2b327356a00489812f66582c6f6d8d4ea8d03ca1c6f036b271f74f1b97f3dc2dcc54a115e13aa484') }}"
    _zoom_build_dir: "/tmp/zoom-build"

  tasks:

    - name: Remove current build
      become: true
      become_user: "{{ aur_builder_user }}"
      kewlfft.aur.aur:
        name: "{{ _zoom_pkg_name }}"
        state: "absent"

    - name: Install zoom if required
      when: _zoom_state == 'present'
      block:

        - name: Ensure zoom build dir is present
          ansible.builtin.file:
            path: "{{ _zoom_build_dir }}"
            state: directory
            mode: "0755"

        - name: Copy PKGBUILD to build dir
          ansible.builtin.template:
            src: ../templates/zoom.pkgbuild.j2
            dest: "{{ _zoom_build_dir }}/PKGBUILD"
            mode: "0644"

        - name: Execute makepkg from local PKGBUILD
          become: true
          become_user: "{{ aur_builder_user }}"
          kewlfft.aur.aur:
            name: "{{ _zoom_pkg_name }}"
            state: "{{ _zoom_state }}"
            use: makepkg
            local_pkgbuild: "{{ _zoom_build_dir }}"

        - name: Clean up zoom build dir
          ansible.builtin.file:
            path: "{{ _zoom_build_dir }}"
            state: absent
