---
- name: "[ ZOOM ]"
  hosts: all

  vars:
    _zoom_state: "{{ zoom_state | default('present') }}"
    _zoom_pkg_name: zoom
    _zoom_pkg_version: "{{ zoom_pkg_version | default('7.1.0') }}"
    _zoom_pkg_subversion: "{{ zoom_pkg_subversion | default('3715') }}"
    _zoom_checksum: "{{ zoom_checksum | default('df795f55bcfbd26c1a6c2cc79dc6a251f9011ca097efcd43f75422652e0ee0f017539f8624aa7e51b7092b66962f24e32454a69c93b7faaaaea8f01b6c4b4463') }}"
    _zoom_build_dir: "/tmp/zoom-build"

  tasks:

    - name: Remove current build
      become: true
      become_user: "{{ aur_builder_user }}"
      kewlfft.aur.aur:
        name: "{{ _zoom_pkg_name }}"
        state: "absent"

    - name: Install zoom if required
      when: _zoom_state == 'present'
      block:

        - name: Ensure zoom build dir is present
          ansible.builtin.file:
            path: "{{ _zoom_build_dir }}"
            state: directory
            mode: "0755"

        - name: Copy PKGBUILD to build dir
          ansible.builtin.template:
            src: ../templates/zoom.pkgbuild.j2
            dest: "{{ _zoom_build_dir }}/PKGBUILD"
            mode: "0644"

        - name: Execute makepkg from local PKGBUILD
          become: true
          become_user: "{{ aur_builder_user }}"
          kewlfft.aur.aur:
            name: "{{ _zoom_pkg_name }}"
            state: "{{ _zoom_state }}"
            use: makepkg
            local_pkgbuild: "{{ _zoom_build_dir }}"

        - name: Clean up zoom build dir
          ansible.builtin.file:
            path: "{{ _zoom_build_dir }}"
            state: absent
